export declare const EMPTY_JSON: {
    version: any;
    objects: any[];
};
export declare const PATH_JSON: {
    version: any;
    objects: {
        version: any;
        type: string;
        originX: string;
        originY: string;
        left: number;
        top: number;
        width: number;
        height: number;
        fill: string;
        stroke: any;
        strokeWidth: number;
        scaleX: number;
        scaleY: number;
        angle: number;
        flipX: boolean;
        flipY: boolean;
        opacity: number;
        path: (string | number)[][];
    }[];
    background: string;
    overlay: string;
};
export declare const PATH_WITHOUT_DEFAULTS_JSON: {
    version: any;
    objects: {
        version: any;
        type: string;
        left: number;
        top: number;
        width: number;
        height: number;
        path: (string | number)[][];
    }[];
    background: string;
    overlay: string;
};
export declare const PATH_OBJ_JSON: {
    version: any;
    type: string;
    originX: string;
    originY: string;
    left: number;
    top: number;
    width: number;
    height: number;
    fill: string;
    stroke: any;
    strokeWidth: number;
    scaleX: number;
    scaleY: number;
    angle: number;
    flipX: boolean;
    flipY: boolean;
    opacity: number;
    path: (string | number)[][];
};
export declare const PATH_DATALESS_JSON: {
    version: any;
    objects: {
        type: string;
        version: any;
        originX: string;
        originY: string;
        left: number;
        top: number;
        width: number;
        height: number;
        fill: string;
        stroke: any;
        strokeWidth: number;
        strokeDashArray: any;
        strokeLineCap: string;
        strokeDashOffset: number;
        strokeLineJoin: string;
        strokeUniform: boolean;
        strokeMiterLimit: number;
        scaleX: number;
        scaleY: number;
        angle: number;
        flipX: boolean;
        flipY: boolean;
        opacity: number;
        shadow: any;
        visible: boolean;
        backgroundColor: string;
        fillRule: string;
        paintFirst: string;
        globalCompositeOperation: string;
        skewX: number;
        skewY: number;
        sourcePath: string;
    }[];
};
export declare const RECT_JSON: {
    version: any;
    objects: {
        type: string;
        version: any;
        originX: string;
        originY: string;
        left: number;
        top: number;
        width: number;
        height: number;
        fill: string;
        stroke: any;
        strokeWidth: number;
        strokeDashArray: any;
        strokeLineCap: string;
        strokeDashOffset: number;
        strokeLineJoin: string;
        strokeUniform: boolean;
        strokeMiterLimit: number;
        scaleX: number;
        scaleY: number;
        angle: number;
        flipX: boolean;
        flipY: boolean;
        opacity: number;
        shadow: any;
        visible: boolean;
        backgroundColor: string;
        fillRule: string;
        paintFirst: string;
        globalCompositeOperation: string;
        skewX: number;
        skewY: number;
        rx: number;
        ry: number;
    }[];
    background: string;
    overlay: string;
};
