import { FabricImage } from '../shapes/Image';
export declare const CANVAS_SVG: string;
export declare const CANVAS_SVG_VIEWBOX: string;
export declare const RECT_JSON: {
    version: any;
    objects: {
        type: string;
        version: any;
        originX: string;
        originY: string;
        left: number;
        top: number;
        width: number;
        height: number;
        fill: string;
        stroke: any;
        strokeWidth: number;
        strokeDashArray: any;
        strokeLineCap: string;
        strokeDashOffset: number;
        strokeLineJoin: string;
        strokeUniform: boolean;
        strokeMiterLimit: number;
        scaleX: number;
        scaleY: number;
        angle: number;
        flipX: boolean;
        flipY: boolean;
        opacity: number;
        shadow: any;
        visible: boolean;
        backgroundColor: string;
        fillRule: string;
        paintFirst: string;
        globalCompositeOperation: string;
        skewX: number;
        skewY: number;
        rx: number;
        ry: number;
    }[];
    background: string;
    overlay: string;
};
export declare const PATH_DATALESS_JSON: {
    version: any;
    objects: {
        type: string;
        version: any;
        originX: string;
        originY: string;
        left: number;
        top: number;
        width: number;
        height: number;
        fill: string;
        stroke: any;
        strokeWidth: number;
        strokeDashArray: any;
        strokeLineCap: string;
        strokeDashOffset: number;
        strokeLineJoin: string;
        strokeUniform: boolean;
        strokeMiterLimit: number;
        scaleX: number;
        scaleY: number;
        angle: number;
        flipX: boolean;
        flipY: boolean;
        opacity: number;
        shadow: any;
        visible: boolean;
        backgroundColor: string;
        fillRule: string;
        paintFirst: string;
        globalCompositeOperation: string;
        skewX: number;
        skewY: number;
        sourcePath: string;
    }[];
};
export declare const PATH_JSON: {
    version: any;
    objects: {
        type: string;
        version: any;
        originX: string;
        originY: string;
        left: number;
        top: number;
        width: number;
        height: number;
        fill: string;
        stroke: any;
        strokeWidth: number;
        scaleX: number;
        scaleY: number;
        angle: number;
        flipX: boolean;
        flipY: boolean;
        opacity: number;
        path: (string | number)[][];
    }[];
    background: string;
    overlay: string;
};
export declare const PATH_WITHOUT_DEFAULTS_JSON: {
    version: any;
    objects: {
        type: string;
        version: any;
        left: number;
        top: number;
        width: number;
        height: number;
        path: (string | number)[][];
    }[];
    background: string;
    overlay: string;
};
export declare const RECT_JSON_WITH_PADDING: {
    version: any;
    objects: {
        type: string;
        version: any;
        originX: string;
        originY: string;
        left: number;
        top: number;
        width: number;
        height: number;
        fill: string;
        stroke: any;
        strokeWidth: number;
        strokeDashArray: any;
        strokeLineCap: string;
        strokeDashOffset: number;
        strokeLineJoin: string;
        strokeUniform: boolean;
        strokeMiterLimit: number;
        scaleX: number;
        scaleY: number;
        angle: number;
        flipX: boolean;
        flipY: boolean;
        opacity: number;
        shadow: any;
        visible: boolean;
        backgroundColor: string;
        fillRule: string;
        paintFirst: string;
        globalCompositeOperation: string;
        skewX: number;
        skewY: number;
        rx: number;
        ry: number;
        padding: number;
        foo: string;
    }[];
};
export declare const IMG_SRC: any;
export declare const IMG_WIDTH = 276;
export declare const IMG_HEIGHT = 110;
export declare const REFERENCE_IMG_OBJECT: Partial<FabricImage & {
    version: string;
    src: string;
    crossOrigin: null;
}>;
