import { ColorInput } from '../../../math/Color';
import { Matrix2D } from '../../../math/Matrix2D';
import { PathBuilder } from '../../../math/PathBuilder';
import { BlendOperation, FillRule, FillStyle, FontStyles, LineCap, LineJoin, Paint, TextAlign, TextBaseline } from '../../Paint';
import { Renderer, RendererProps, RenderOptions } from '..';
export declare class CanvasRenderer extends Renderer {
    renderType: string;
    domElement: HTMLCanvasElement;
    ctx: CanvasRenderingContext2D;
    constructor();
    initContext(options: RendererProps): Promise<void>;
    clear(): void;
    transform(a: number, b: number, c: number, d: number, e: number, f: number): void;
    setTransform(a: number, b: number, c: number, d: number, e: number, f: number): void;
    getTransform(): Matrix2D;
    resetTransform(): void;
    translate(x: number, y: number): void;
    scale(sx: number, sy: number): void;
    rotate(angle: number): void;
    roundRect(x: number, y: number, width: number, height: number, radius: number | number[]): void;
    setGlobalAlpha(alpha: number): void;
    setBlend(operation: BlendOperation): void;
    setLineWidth(width: number): void;
    setLineJoin(lineJoin: LineJoin): void;
    setLineCap(lineCap: LineCap): void;
    setLineDash(lineDash: number[]): void;
    setLineDashOffset(lineDashOffset: number): void;
    setMiterLimit(miterLimit: number): void;
    getCanvasFillStyle(fillStyle: FillStyle): string | CanvasGradient | CanvasPattern;
    setFillStyle(fillStyle: FillStyle): void;
    setStrokeStyle(fillStyle: FillStyle): void;
    setShadowColor(shadowColor: ColorInput): void;
    setShadowOffsetX(shadowOffsetX: number): void;
    setShadowOffsetY(shadowOffsetY: number): void;
    setShadowBlur(shadowBlur: number): void;
    setTextBaseline(textBaseline: TextBaseline): void;
    setTextAlign(textAlign: TextAlign): void;
    setWordSpacing(wordSpacing: number): void;
    setLetterSpacing(letterSpacing: number): void;
    setFont(style: Partial<FontStyles>): void;
    fill(fillRule: FillRule): void;
    stroke(): void;
    fillText(text: string, x: number, y: number): void;
    drawRect(x: number, y: number, width: number, height: number, paint: Paint): void;
    drawCircle(x: number, y: number, radius: number, paint: Paint): void;
    drawRoundRect(x: number, y: number, width: number, height: number, radius: number | number[], paint: Paint): void;
    drawEllipse(x: number, y: number, radiusX: number, radiusY: number, paint: Paint): void;
    drawPath(path: PathBuilder, paint: Paint): void;
    drawImage(image: CanvasImageSource, x: number, y: number, w: number, h: number): void;
    render(renderOptions: RenderOptions): void;
    save(): void;
    restore(): void;
    beginPath(): void;
    closePath(): void;
    moveTo(x: number, y: number): void;
    lineTo(x: number, y: number): void;
    arcTo(x1: number, y1: number, x2: number, y2: number, radius: number): void;
    quadraticCurveTo(x1: number, y1: number, x2: number, y2: number): void;
    bezierCurveTo(x1: number, y1: number, x2: number, y2: number, x3: number, y3: number): void;
    rect(x: number, y: number, width: number, height: number): void;
    arc(x: number, y: number, radius: number, startAngle: number, endAngle: number, ccw: boolean): void;
    ellipse(x: number, y: number, radiusX: number, radiusY: number, rotation: number, startAngle: number, endAngle: number, ccw: boolean): void;
}
