import { default as Body } from './body/Body';
import { default as Composite } from './body/Composite';
import { default as World } from './body/World';
import { default as Collision } from './collision/Collision';
import { default as Contact } from './collision/Contact';
import { default as Detector } from './collision/Detector';
import { default as Grid } from './collision/Grid';
import { default as Pair } from './collision/Pair';
import { default as Pairs } from './collision/Pairs';
import { default as Query } from './collision/Query';
import { default as Resolver } from './collision/Resolver';
import { default as SAT } from './collision/SAT';
import { default as Constraint } from './constraint/Constraint';
import { default as MouseConstraint } from './constraint/MouseConstraint';
import { default as Common } from './core/Common';
import { default as Engine } from './core/Engine';
import { default as Events } from './core/Events';
import { default as Matter } from './core/Matter';
import { default as Mouse } from './core/Mouse';
import { default as Plugin } from './core/Plugin';
import { default as Runner } from './core/Runner';
import { default as Sleeping } from './core/Sleeping';
import { default as Bodies } from './factory/Bodies';
import { default as Composites } from './factory/Composites';
import { default as Axes } from './geometry/Axes';
import { default as Bounds } from './geometry/Bounds';
import { default as Svg } from './geometry/Svg';
import { default as Vector } from './geometry/Vector';
import { default as Vertices } from './geometry/Vertices';
import { default as Render } from './render/Render';
export * as Body from './body/Body';
export * as Composite from './body/Composite';
export * as World from './body/World';
export * as Collision from './collision/Collision';
export * as Contact from './collision/Contact';
export * as Detector from './collision/Detector';
export * as Grid from './collision/Grid';
export * as Pair from './collision/Pair';
export * as Pairs from './collision/Pairs';
export * as Query from './collision/Query';
export * as Resolver from './collision/Resolver';
export * as SAT from './collision/SAT';
export * as Constraint from './constraint/Constraint';
export * as MouseConstraint from './constraint/MouseConstraint';
export * as Common from './core/Common';
export * as Engine from './core/Engine';
export * as Events from './core/Events';
export * as Matter from './core/Matter';
export * as Mouse from './core/Mouse';
export * as Plugin from './core/Plugin';
export * as Runner from './core/Runner';
export * as Sleeping from './core/Sleeping';
export * as Bodies from './factory/Bodies';
export * as Composites from './factory/Composites';
export * as Axes from './geometry/Axes';
export * as Bounds from './geometry/Bounds';
export * as Svg from './geometry/Svg';
export * as Vector from './geometry/Vector';
export * as Vertices from './geometry/Vertices';
export * as Render from './render/Render';
export default class MatterModule extends Matter {
    static Axes: typeof Axes;
    static Bodies: typeof Bodies;
    static Body: typeof Body;
    static Bounds: typeof Bounds;
    static Collision: typeof Collision;
    static Common: typeof Common;
    static Composite: typeof Composite;
    static Composites: typeof Composites;
    static Constraint: typeof Constraint;
    static Contact: typeof Contact;
    static Detector: typeof Detector;
    static Engine: typeof Engine;
    static Events: typeof Events;
    static Grid: typeof Grid;
    static Mouse: typeof Mouse;
    static MouseConstraint: typeof MouseConstraint;
    static Pair: typeof Pair;
    static Pairs: typeof Pairs;
    static Plugin: typeof Plugin;
    static Query: typeof Query;
    static Render: typeof Render;
    static Resolver: typeof Resolver;
    static Runner: typeof Runner;
    static SAT: typeof SAT;
    static Sleeping: typeof Sleeping;
    static Svg: typeof Svg;
    static Vector: typeof Vector;
    static Vertices: typeof Vertices;
    static World: typeof World;
}
