import { default as Angle } from './angle/';
import { default as Distance } from './distance/';
import { default as Easing } from './easing/';
import { default as Fuzzy } from './fuzzy/';
import { default as Interpolation } from './interpolation/';
import { default as Pow2 } from './pow2/';
import { default as Snap } from './snap/';
import { default as RandomDataGenerator } from './random-data-generator/RandomDataGenerator';
import { default as Average } from './Average';
import { default as Bernstein } from './Bernstein';
import { default as Between } from './Between';
import { default as CatmullRom } from './CatmullRom';
import { default as CeilTo } from './CeilTo';
import { default as Clamp } from './Clamp';
import { default as DegToRad } from './DegToRad';
import { default as Difference } from './Difference';
import { default as Euler } from './Euler';
import { default as Factorial } from './Factorial';
import { default as FloatBetween } from './FloatBetween';
import { default as FloorTo } from './FloorTo';
import { default as FromPercent } from './FromPercent';
import { default as GetSpeed } from './GetSpeed';
import { default as IsEven } from './IsEven';
import { default as IsEvenStrict } from './IsEvenStrict';
import { default as Linear } from './Linear';
import { default as LinearXY } from './LinearXY';
import { default as MaxAdd } from './MaxAdd';
import { default as Median } from './Median';
import { default as MinSub } from './MinSub';
import { default as Percent } from './Percent';
import { default as RadToDeg } from './RadToDeg';
import { default as RandomXY } from './RandomXY';
import { default as RandomXYZ } from './RandomXYZ';
import { default as RandomXYZW } from './RandomXYZW';
import { default as Rotate } from './Rotate';
import { default as RotateAround } from './RotateAround';
import { default as RotateAroundDistance } from './RotateAroundDistance';
import { default as RotateTo } from './RotateTo';
import { default as RoundAwayFromZero } from './RoundAwayFromZero';
import { default as RoundTo } from './RoundTo';
import { default as SinCosTableGenerator } from './SinCosTableGenerator';
import { default as SmootherStep } from './SmootherStep';
import { default as SmoothStep } from './SmoothStep';
import { default as ToXY } from './ToXY';
import { default as TransformXY } from './TransformXY';
import { default as Within } from './Within';
import { default as Wrap } from './Wrap';
import { default as Vector2 } from './Vector2';
import { default as Vector3 } from './Vector3';
import { default as Vector4 } from './Vector4';
import { default as Matrix3 } from './Matrix3';
import { default as Matrix4 } from './Matrix4';
import { default as Quaternion } from './Quaternion';
import { default as RotateVec3 } from './RotateVec3';
export default PhaserMath;
declare namespace PhaserMath {
    export { Angle };
    export { Distance };
    export { Easing };
    export { Fuzzy };
    export { Interpolation };
    export { Pow2 };
    export { Snap };
    export { RandomDataGenerator };
    export { Average };
    export { Bernstein };
    export { Between };
    export { CatmullRom };
    export { CeilTo };
    export { Clamp };
    export { DegToRad };
    export { Difference };
    export { Euler };
    export { Factorial };
    export { FloatBetween };
    export { FloorTo };
    export { FromPercent };
    export { GetSpeed };
    export { IsEven };
    export { IsEvenStrict };
    export { Linear };
    export { LinearXY };
    export { MaxAdd };
    export { Median };
    export { MinSub };
    export { Percent };
    export { RadToDeg };
    export { RandomXY };
    export { RandomXYZ };
    export { RandomXYZW };
    export { Rotate };
    export { RotateAround };
    export { RotateAroundDistance };
    export { RotateTo };
    export { RoundAwayFromZero };
    export { RoundTo };
    export { SinCosTableGenerator };
    export { SmootherStep };
    export { SmoothStep };
    export { ToXY };
    export { TransformXY };
    export { Within };
    export { Wrap };
    export { Vector2 };
    export { Vector3 };
    export { Vector4 };
    export { Matrix3 };
    export { Matrix4 };
    export { Quaternion };
    export { RotateVec3 };
}
