/**
 * WebGPU renderer for mini3d.
 *
 * Mirrors `WebGLRenderer`'s scene traversal, sorting, culling and material
 * interpretation so both backends produce the same image, but drives a
 * `GPUDevice` instead of a GL context.
 *
 * ## Deliberate differences from WebGL
 *
 * - **Clip-space depth**: `Matrix4.makePerspective`/`makeOrthographic` ignore
 *   `camera.coordinateSystem` (the parameter is `void`ed), so the projection
 *   matrix is remapped in *software* before upload: every camera matrix is
 *   pre-multiplied by `CLIP_SPACE_REMAP` (`z' = z*0.5 + w*0.5`) on its way into
 *   `FrameUniforms`. The camera's own `projectionMatrix` is never mutated, so
 *   `unproject()` and the WebGL backend keep working on the same camera.
 * - **`polygonOffset`**: WebGPU has no depth-bias state outside a shadow pass,
 *   so `material.polygonOffset*` is ignored here (documented no-op).
 * - **Pipeline creation is async**: the first frame that introduces a material
 *   combination skips that draw while `createRenderPipelineAsync()` runs. Use
 *   `await renderer.compile(scene, camera)` to pre-warm everything first.
 * - **Stencil**: not exposed; `parameters.stencil` is accepted but unused.
 *
 * ## Documented choices for the "pick one" decisions
 *
 * 1. *Topology expansion* 閳?`'line-strip'` and `points` are expanded into
 *    `'line-list'`/`'point-list'` by generating an **index buffer** (see
 *    `WgpuGeometries#expansion:lineStrip`): `0,1, 1,2, 2,3, 閳ヮ泦 and an identity
 *    map respectively. No vertex data is duplicated.
 * 2. *`flipY`* 閳?implemented by flipping pixel **rows on the CPU during upload**
 *    (canvas round-trip for image sources) rather than negating V, because
 *    negating V through `uvTransform` would flip the tangent basis used by the
 *    normal-map perturbation. See `WgpuTextures`.
 * 3. *Mipmaps* 閳?generated by a bundled **compute** box-filter chain; if the
 *    device cannot run it, mipmapped `minFilter`s degrade to `'linear'` and a
 *    warning is emitted once.
 * 4. *Texture background* 閳?a tiny purpose-built WGSL fullscreen blit inside
 *    this backend (`BACKGROUND_WGSL` in `WgpuPipelines.ts`), sampled with
 *    V-down UVs so an unflipped background image appears right way up.
 */

import { Color } from '../../math/Color';
import { Vector3 } from '../../math/Vector3';
import { Sphere } from '../../math/Sphere';
import { LightState, collectLights } from '../../core/LightState';
import type { Scene } from '../../core/Scene';
import type { Camera } from '../../core/Camera';
import type { Object3D } from '../../core/Object3D';
import type { BufferGeometry, DrawMode } from '../../core/BufferGeometry';
import type { Material } from '../../materials/Material';
import { Texture } from '../../textures/Texture';
import type {
  Renderer,
  RendererCapabilities,
  RendererInfo,
  RendererParameters,
} from '../../core/types';
import {
  FRAME_UNIFORM_BYTES,
  FRAME_UNIFORM_FLOATS,
  packFrameUniforms,
  writeClipSpaceRemap,
  writeViewProjection,
} from './WgpuUniforms';
import {
  PIPELINE_ATTRIBUTES,
  TOPOLOGY_FOR_DRAW_MODE,
  WgpuGeometries,
  topologySupportsIndexed,
  vertexBufferLayouts,
  vertexLayoutKey,
} from './WgpuGeometries';
import type { WgpuGeometryRecord } from './WgpuGeometries';
import { WgpuTextures } from './WgpuTextures';
import { WgpuPipelines } from './WgpuPipelines';
import type { WgpuPipelineRequest } from './WgpuPipelines';
import { safeWriteBuffer } from './WgpuUploads';
import type { RenderTarget } from '../../textures/RenderTarget';

/** Parameters accepted by `WebGPURenderer.create()` / the constructor. */
export interface WebGPURendererParameters extends RendererParameters {
  /**
   * Milliseconds to wait for `requestAdapter()` / `requestDevice()` before
   * giving up. Adapter acquisition can hang indefinitely when the browser
   * exposes a stub adapter (for example headless Chrome without a real GPU), so
   * this bounds the wait. Defaults to 5000 ms.
   */
  deviceTimeout?: number;
}

/** Resolved parameters with every default applied. */
export interface ResolvedWebGPUParameters {
  canvas: HTMLCanvasElement | OffscreenCanvas | null;
  pixelRatio: number;
  antialias: boolean;
  powerPreference: 'default' | 'high-performance' | 'low-power';
  forceFallbackAdapter: boolean;
  preserveDrawingBuffer: boolean;
  depth: boolean;
  stencil: boolean;
  premultipliedAlpha: boolean;
  alpha: boolean;
  debug: boolean;
  cacheLimit: number;
  deviceTimeout: number;
}

/**
 * Rejects with a descriptive error when `promise` does not settle in time.
 * Used for the WebGPU adapter/device handshake, which has no built-in timeout.
 */
async function withTimeout<T>(promise: Promise<T>, ms: number, label: string): Promise<T> {
  if (!Number.isFinite(ms) || ms <= 0) return promise;
  let timer: ReturnType<typeof setTimeout> | undefined;
  try {
    return await Promise.race([
      promise,
      new Promise<never>((_resolve, reject) => {
        timer = setTimeout(
          () => reject(new Error(`mini3d.WebGPURenderer: ${label} did not settle within ${ms} ms`)),
          ms,
        );
      }),
    ]);
  } finally {
    if (timer !== undefined) clearTimeout(timer);
  }
}

/** Depth format used for every render pass. */
const DEPTH_FORMAT: GPUTextureFormat = 'depth24plus';

/** Default canvas size when the environment gives us nothing better. */
const DEFAULT_WIDTH = 300;
const DEFAULT_HEIGHT = 150;

/** A queued draw, mirroring `WebGLRenderer`'s private `RenderItem`. */
interface RenderItem {
  object: Object3D & {
    geometry: BufferGeometry;
    material: Material | Material[];
  };
  material: Material;
  materialIndex: number;
  /** Ascending sort key: opaque first (`false`), transparent second (`true`). */
  transparent: boolean;
  z: number;
  order: number;
}

/** Resolves user parameters, filling in every default. */
export function resolveWebGPUParameters(
  parameters: WebGPURendererParameters = {},
): ResolvedWebGPUParameters {
  return {
    canvas: parameters.canvas ?? null,
    pixelRatio: parameters.pixelRatio ?? defaultPixelRatio(),
    antialias: parameters.antialias ?? true,
    powerPreference: parameters.powerPreference ?? 'default',
    forceFallbackAdapter: parameters.forceFallbackAdapter ?? false,
    preserveDrawingBuffer: parameters.preserveDrawingBuffer ?? false,
    depth: parameters.depth ?? true,
    stencil: parameters.stencil ?? false,
    premultipliedAlpha: parameters.premultipliedAlpha ?? true,
    alpha: parameters.alpha ?? false,
    debug: parameters.debug ?? false,
    cacheLimit: parameters.cacheLimit ?? 512,
    deviceTimeout: parameters.deviceTimeout ?? 5000,
  };
}

function defaultPixelRatio(): number {
  if (typeof window === 'undefined') return 1;
  return window.devicePixelRatio || 1;
}

/** True when `navigator.gpu` exists in this environment. */
function navigatorGpu(): GPU | null {
  const nav = (globalThis as { navigator?: { gpu?: GPU } }).navigator;
  return nav?.gpu ?? null;
}

/**
 * WebGPU implementation of the `Renderer` interface.
 *
 * Construct it directly with an existing device, or use the async
 * `WebGPURenderer.create()` factory which resolves the adapter/device/context
 * for you.
 */
export class WebGPURenderer implements Renderer {
  readonly backend = 'webgpu' as const;
  readonly canvas: HTMLCanvasElement | OffscreenCanvas;
  readonly capabilities: RendererCapabilities;
  readonly info: RendererInfo;

  readonly parameters: ResolvedWebGPUParameters;
  readonly device: GPUDevice;
  readonly context: GPUCanvasContext;
  readonly format: GPUTextureFormat;

  /** Geometry buffer cache (exposed for diagnostics, like `WebGLRenderer.geometries`). */
  readonly geometries: WgpuGeometries;
  /** Texture + sampler cache. */
  readonly textures: WgpuTextures;
  /** Pipeline + uniform cache. */
  readonly pipelines: WgpuPipelines;

  pixelRatio: number;
  autoClear = true;
  /** Clear the depth buffer between `render()` calls. */
  autoClearDepth = true;
  /** Accepted for parity; WebGPU has no stencil attachment here. */
  autoClearStencil = false;
  /** Toggle frustum culling globally. */
  frustumCulling = true;

  private readonly clearColor = new Color(0x000000);
  private clearAlpha = 0;
  private readonly lightState = new LightState();
  private readonly renderList: RenderItem[] = [];
  private readonly boundSphere = new Sphere();
  private readonly cameraPosition = new Vector3();
  private readonly frameData = new Float32Array(FRAME_UNIFORM_FLOATS);
  private readonly gpuProjection = new Float32Array(16);
  private readonly gpuViewProjection = new Float32Array(16);

  private readonly frameBuffer: GPUBuffer;
  private readonly frameBindGroup: GPUBindGroup;
  private depthTexture: GPUTexture | null = null;
  /** Target currently bound, or 
ull for the canvas. */
  private _renderTarget: RenderTarget | null = null;
  private depthView: GPUTextureView | null = null;
  private frame = 0;
  private disposed = false;
  private deviceLost = false;
  private _currentScene: Scene | null = null;
  private readonly maxTextureDimension: number;

  constructor(
    device: GPUDevice,
    context: GPUCanvasContext,
    params: ResolvedWebGPUParameters,
    format?: GPUTextureFormat,
  ) {
    this.device = device;
    this.context = context;
    this.parameters = params;
    this.pixelRatio = params.pixelRatio;

    const canvas = params.canvas ?? (context.canvas as HTMLCanvasElement | OffscreenCanvas);
    if (!canvas) {
      throw new Error(
        'mini3d.WebGPURenderer: the GPUCanvasContext has no canvas; pass `{ canvas }`.',
      );
    }
    this.canvas = canvas;

    this.maxTextureDimension = device.limits.maxTextureDimension2D;
    this.format = format ?? configuredFormat(context) ?? 'bgra8unorm';
    this.capabilities = {
      backend: 'webgpu',
      maxTextureSize: this.maxTextureDimension,
      maxTextureUnits: 16,
      maxVertexAttributes: device.limits.maxVertexAttributes,
      maxSamples: 4,
      precision: { vertex: 'highp(23)', fragment: 'highp(23)' },
      isWebGL2: true,
      features: {
        vertexArrayObject: true,
        instancedArrays: true,
        elementIndexUint: true,
        textureFloat: true,
        textureHalfFloat: true,
        depthTexture: true,
        colorBufferFloat: true,
        anisotropy: false,
        timestampQuery: device.features.has('timestamp-query'),
      },
      info: 'WebGPU',
    };

    this.info = {
      render: { frame: 0, calls: 0, triangles: 0, lines: 0, points: 0, time: 0 },
      memory: { geometries: 0, textures: 0, programs: 0 },
    };

    this.pipelines = new WgpuPipelines(device, {
      color: this.format,
      depth: DEPTH_FORMAT,
      sampleCount: 1,
    });
    this.textures = new WgpuTextures(device, this.pipelines.objectLayout);
    this.geometries = new WgpuGeometries(device);

    this.frameBuffer = device.createBuffer({
      label: 'mini3d.frame',
      size: FRAME_UNIFORM_BYTES,
      usage: GPUBufferUsage.UNIFORM | GPUBufferUsage.COPY_DST,
    });
    this.frameBindGroup = device.createBindGroup({
      label: 'mini3d.frame',
      layout: this.pipelines.frameLayout,
      entries: [{ binding: 0, resource: { buffer: this.frameBuffer } }],
    });

    this.watchDeviceLost();

    const width = (canvas as HTMLCanvasElement).width || DEFAULT_WIDTH;
    const height = (canvas as HTMLCanvasElement).height || DEFAULT_HEIGHT;
    this.setSize(
      Math.floor(width / this.pixelRatio) || DEFAULT_WIDTH,
      Math.floor(height / this.pixelRatio) || DEFAULT_HEIGHT,
      false,
    );
    this.setClearColor(0x000000, 0);
  }

  // --------------------------------------------------------------- statics --

  /** `true` when `navigator.gpu` exists (cheap, no adapter request). */
  static isAvailable(): boolean {
    return navigatorGpu() !== null;
  }

  /**
   * Resolves an adapter + device, obtains a `webgpu` canvas context, configures
   * it, and constructs the renderer.
   */
  static async create(params: WebGPURendererParameters = {}): Promise<WebGPURenderer> {
    const gpu = navigatorGpu();
    if (!gpu) {
      throw new Error(
        'mini3d.WebGPURenderer: WebGPU is not available (navigator.gpu is undefined).',
      );
    }

    const resolved = resolveWebGPUParameters(params);
    let canvas = resolved.canvas;
    if (!canvas) {
      if (typeof document === 'undefined' || typeof document.createElement !== 'function') {
        throw new Error(
          'mini3d.WebGPURenderer: no canvas supplied and `document` is unavailable (headless?); pass `{ canvas }`.',
        );
      }
      canvas = document.createElement('canvas');
      canvas.width = DEFAULT_WIDTH;
      canvas.height = DEFAULT_HEIGHT;
      resolved.canvas = canvas;
    }

    const adapter = await withTimeout(
      gpu.requestAdapter({
        // `GPUPowerPreference` only accepts 'low-power' / 'high-performance';
        // omitting the field is how a "default" hint is expressed.
        ...(resolved.powerPreference === 'default'
          ? {}
          : { powerPreference: resolved.powerPreference }),
        forceFallbackAdapter: resolved.forceFallbackAdapter,
      }),
      resolved.deviceTimeout,
      'requestAdapter()',
    );
    if (!adapter) {
      throw new Error(
        'mini3d.WebGPURenderer: requestAdapter() returned null (no compatible adapter).',
      );
    }

    // `GPUAdapter.requestDevice()` can hang indefinitely when the adapter is a
    // stub (headless Chrome without a real GPU), so it is bounded.
    const device = await withTimeout(
      (adapter as GPUAdapter).requestDevice(),
      resolved.deviceTimeout,
      'requestDevice()',
    );
    const context = (canvas as HTMLCanvasElement).getContext('webgpu') as GPUCanvasContext | null;
    if (!context) {
      throw new Error(
        'mini3d.WebGPURenderer: unable to obtain a "webgpu" canvas context from the supplied canvas.',
      );
    }

    const format = gpu.getPreferredCanvasFormat();
    context.configure({
      device,
      format,
      alphaMode: resolved.alpha ? 'premultiplied' : 'opaque',
    });

    return new WebGPURenderer(device, context, resolved, format);
  }

  /** Pre-creates every pipeline and texture a scene needs. */
  async compile(scene: Scene, camera: Camera): Promise<void> {
    if (this.disposed) {
      throw new Error('mini3d.WebGPURenderer: compile() called after dispose()');
    }
    camera.updateMatrices();
    scene.updateMatrixWorld();
    this._currentScene = scene;
    collectLights(scene, this.lightState, camera);

    this.renderList.length = 0;
    this.projectObject(scene, camera);

    for (const item of this.renderList) {
      const geometry = item.object.geometry;
      const record = this.geometries.prepare(geometry);
      const request = this.pipelineRequest(item.material, geometry, record);
      if (!request) continue;
      // Pre-warm the texture bind group too; the pipeline itself is awaited
      // below by `settle()`.
      this.pipelines.uploadObjectUniforms(item.material, item.object, this.textures);
      this.pipelines.request(request);
    }

    await this.pipelines.settle();
    const background = scene.background;
    if (background instanceof Texture) this.textures.upload(background);
  }

  // ------------------------------------------------------------ capabilities --

  get width(): number {
    return (this.canvas as HTMLCanvasElement).width;
  }

  get height(): number {
    return (this.canvas as HTMLCanvasElement).height;
  }

  get domWidth(): number {
    return this.canvas.width;
  }

  get domHeight(): number {
    return this.canvas.height;
  }

  // ------------------------------------------------------------- sizing ----

  setSize(width: number, height: number, updateStyle = true): void {
    const pixelWidth = clampDimension(width * this.pixelRatio, this.maxTextureDimension);
    const pixelHeight = clampDimension(height * this.pixelRatio, this.maxTextureDimension);
    this.canvas.width = pixelWidth;
    this.canvas.height = pixelHeight;
    if (updateStyle && typeof (this.canvas as HTMLCanvasElement).style !== 'undefined') {
      const style = (this.canvas as HTMLCanvasElement).style;
      style.width = `${Math.max(1, Math.floor(width))}px`;
      style.height = `${Math.max(1, Math.floor(height))}px`;
    }
    this.ensureDepthTexture();
  }

  setPixelRatio(ratio: number): void {
    const previous = this.pixelRatio;
    this.pixelRatio = ratio;
    const domWidth = (this.canvas.width || DEFAULT_WIDTH) / previous;
    const domHeight = (this.canvas.height || DEFAULT_HEIGHT) / previous;
    this.setSize(domWidth, domHeight, false);
  }

  private ensureDepthTexture(): void {
    const width = Math.max(1, this.canvas.width);
    const height = Math.max(1, this.canvas.height);
    if (
      this.depthTexture &&
      this.depthTexture.width === width &&
      this.depthTexture.height === height
    ) {
      return;
    }
    this.depthTexture?.destroy();
    this.depthTexture = this.device.createTexture({
      label: 'mini3d.depth',
      size: { width, height, depthOrArrayLayers: 1 },
      format: DEPTH_FORMAT,
      usage: GPUTextureUsage.RENDER_ATTACHMENT,
    });
    this.depthView = this.depthTexture.createView();
  }

  // -------------------------------------------------------------- clear ----

  setClearColor(color: number | string | Color | null, alpha = 1): this {
    if (color !== null && color !== undefined) this.clearColor.set(color);
    this.clearAlpha = alpha;
    return this;
  }

  setClearAlpha(alpha: number): void {
    this.clearAlpha = alpha;
  }

  getClearColor(target: Color = new Color()): Color {
    return target.copy(this.clearColor);
  }

  getClearAlpha(): number {
    return this.clearAlpha;
  }

  /**
   * Clears the current swap-chain image. WebGPU has no stencil attachment in
   * this renderer, so `stencil` is accepted and ignored (like `polygonOffset`).
   */
  clear(color = true, depth = this.autoClearDepth, stencil = this.autoClearStencil): void {
    void stencil;
    if (this.disposed || this.deviceLost) return;
    const encoder = this.device.createCommandEncoder({ label: 'mini3d.clear' });
    const pass = encoder.beginRenderPass(this.renderPassDescriptor(color, depth, null));
    pass.end();
    const command = encoder.finish();
    this.device.queue.submit([command]);
    this.present();
  }

  // ------------------------------------------------------------- render ----

  render(scene: Scene, camera: Camera): void {
    if (this.disposed) {
      throw new Error('mini3d.WebGPURenderer: render() called after dispose()');
    }
    if (this.deviceLost) return;
    const started = now();

    camera.updateMatrices();
    (scene as Object3D).updateMatrixWorld();
    this._currentScene = scene;

    collectLights(scene, this.lightState, camera);

    // Per-frame counters, matching the WebGL backend.
    this.info.render.calls = 0;
    this.info.render.triangles = 0;
    this.info.render.lines = 0;
    this.info.render.points = 0;

    this.renderList.length = 0;
    this.projectObject(scene, camera);
    // Opaque front-to-back, then transparent back-to-front 閳?identical to the
    // WebGL backend's ordering.
    this.renderList.sort(compareRenderItems);

    this.ensureDepthTexture();
    this.uploadFrameUniforms(scene, camera);

    const background = scene.background;
    const backgroundColor = background instanceof Color ? background : null;
    const backgroundTexture = background instanceof Texture ? background : null;

    const clearColor = backgroundColor !== null || this.autoClear;
    const clearDepth = this.autoClearDepth;

    const encoder = this.device.createCommandEncoder({ label: 'mini3d.frame' });
    // The viewport follows the bound target: a render target's own size, or the
    // canvas drawing buffer.
    const target = this._renderTarget;
    const viewWidth = Math.max(1, target ? target.width : this.canvas.width);
    const viewHeight = Math.max(1, target ? target.height : this.canvas.height);
    const pass = encoder.beginRenderPass(
      this.renderPassDescriptor(clearColor, clearDepth, backgroundColor),
    );
    pass.setViewport(
      target ? target.viewport.x : 0,
      target ? target.viewport.y : 0,
      target ? target.viewport.width : viewWidth,
      target ? target.viewport.height : viewHeight,
      0,
      1,
    );
    pass.setScissorRect(
      target && target.scissorTest ? target.scissor.x : 0,
      target && target.scissorTest ? target.scissor.y : 0,
      target && target.scissorTest ? target.scissor.width : viewWidth,
      target && target.scissorTest ? target.scissor.height : viewHeight,
    );

    for (const item of this.renderList) {
      this.drawItem(pass, item, camera);
    }

    if (backgroundTexture) this.drawBackgroundTexture(pass, backgroundTexture);

    pass.setBindGroup(0, null);
    pass.setBindGroup(1, null);
    pass.end();

    const command = encoder.finish();
    this.device.queue.submit([command]);
    this.present();

    this.info.render.frame = ++this.frame;
    this.info.render.time = now() - started;
    this.info.memory.geometries = this.geometries.count;
    this.info.memory.textures = this.textures.count;
    this.info.memory.programs = this.pipelines.size;
  }

  // ------------------------------------------------------- render target ----

  /**
   * Redirects subsequent draws into `target`, or back to the canvas when `null`.
   *
   * WebGPU has no persistent framebuffer binding: the target is recorded here and
   * turned into the colour/depth attachments of the next `render()` pass, so this
   * only validates and stores. The swap-chain texture is acquired at pass time,
   * which is why a target change never needs a reconfigure.
   */
  setRenderTarget(target: RenderTarget | null): void {
    if (this.disposed) return;
    this._renderTarget = target;
    if (target === null) return;
    if (target.samples > 1) {
      throw new Error(
        'mini3d.WebGPURenderer: multisampled render targets are not implemented yet; ' +
          'use `RenderTarget({ samples: 0 })` (the default) on this backend.',
      );
    }
  }

  /** The target currently bound, or `null` for the canvas. */
  getRenderTarget(): RenderTarget | null {
    return this._renderTarget;
  }

  /** Describes the single render pass of a frame. */
  private renderPassDescriptor(
    clearColor: boolean,
    clearDepth: boolean,
    background: Color | null,
  ): GPURenderPassDescriptor {
    const color = background
      ? { r: background.r, g: background.g, b: background.b, a: 1 }
      : { r: this.clearColor.r, g: this.clearColor.g, b: this.clearColor.b, a: this.clearAlpha };

    const target = this._renderTarget;
    const colorAttachments: GPURenderPassColorAttachment[] = [
      {
        view:
          target !== null
            ? this.textures.renderTargetView(target.texture)
            : this.context.getCurrentTexture().createView(),
        clearValue: color,
        loadOp: clearColor ? 'clear' : 'load',
        storeOp: 'store',
      },
    ];

    const descriptor: GPURenderPassDescriptor = {
      label: 'mini3d.frame',
      colorAttachments,
    };

    // A target's own depth attachment wins; otherwise the renderer's shared
    // depth texture backs the canvas pass.
    const targetDepth = target?.depthTexture ?? null;
    if (targetDepth) {
      descriptor.depthStencilAttachment = {
        view: this.textures.renderTargetView(targetDepth),
        depthClearValue: 1,
        depthLoadOp: clearDepth ? 'clear' : 'load',
        depthStoreOp: 'store',
      };
    } else if (target !== null) {
      if (clearDepth) this.deferredDepthClear = true;
    } else if (this.depthView) {
      descriptor.depthStencilAttachment = {
        view: this.depthView,
        depthClearValue: 1,
        depthLoadOp: clearDepth ? 'clear' : 'load',
        depthStoreOp: 'store',
      };
    }
    return descriptor;
  }

  /** Set when a target without a depth attachment still needs one cleared. */
  private deferredDepthClear = false;

  /**
   * Placeholder for the implicit swap-chain present. WebGPU presents when the
   * frame ends, so there is nothing to do; the hook exists so a future
   * `preserveDrawingBuffer` implementation has an obvious home.
   */
  private present(): void {
    /* canvas presents implicitly */
  }

  // --------------------------------------------------------- scene walk ----

  /** Walks the graph once and queues every visible, in-frustum draw. */
  private projectObject(object: Object3D, camera: Camera): void {
    if (!object.visible) return;

    const renderable = object as Object3D & {
      isMesh?: boolean;
      isLine?: boolean;
      isPoints?: boolean;
      isSprite?: boolean;
      geometry?: BufferGeometry;
      material?: Material | Material[];
    };

    if (
      (renderable.isMesh || renderable.isLine || renderable.isPoints) &&
      renderable.geometry &&
      renderable.material &&
      object.layers.test(camera.layers)
    ) {
      if (this.isVisible(object, camera, renderable.geometry)) {
        this.pushRenderItem(object as never, renderable.material, camera);
      }
    } else if (renderable.isSprite && renderable.material) {
      // Sprites have no geometry of their own; the WebGL backend renders them
      // through the points path. WebGPU requires a geometry, so they are
      // skipped with a one-time warning rather than crashing the frame.
      this.warnSpriteOnce();
    }

    const children = object.children;
    for (let i = 0; i < children.length; i++) this.projectObject(children[i], camera);
  }

  private spriteWarned = false;

  private warnSpriteOnce(): void {
    if (this.spriteWarned) return;
    this.spriteWarned = true;
    console.warn(
      'mini3d.WebGPURenderer: Sprite rendering is not implemented in the WebGPU backend; ' +
        'use a Mesh with a quad geometry instead.',
    );
  }

  /** Frustum test against the object's world-space bounding sphere. */
  private isVisible(object: Object3D, camera: Camera, geometry: BufferGeometry): boolean {
    if (!this.frustumCulling || !object.frustumCulled) return true;
    if (!geometry.attributes.position) return true;
    const holder = object as Object3D & { boundingSphere?: Sphere | null };
    let sphere = holder.boundingSphere ?? null;
    if (!sphere) {
      sphere = geometry.getBoundingSphere().clone();
      holder.boundingSphere = sphere;
    }
    this.boundSphere.copy(sphere).applyMatrix4(object.matrixWorld);
    return camera.frustum.intersectsSphere(this.boundSphere);
  }

  /** Expands a material (or material array) into one or more render items. */
  private pushRenderItem(
    object: Object3D & { geometry?: BufferGeometry },
    material: Material | Material[],
    camera: Camera,
  ): void {
    if (Array.isArray(material)) {
      if (material.length === 0) return;
      const groups = object.geometry?.groups ?? [];
      if (groups.length === 0) {
        for (let i = 0; i < material.length; i++) {
          this.pushSingle(object as never, material[i], i, camera);
        }
      } else {
        const seen = new Set<number>();
        for (const group of groups) {
          const index = Math.min(group.materialIndex, material.length - 1);
          if (seen.has(index)) continue;
          seen.add(index);
          this.pushSingle(object as never, material[index], index, camera);
        }
      }
      return;
    }
    this.pushSingle(object as never, material, 0, camera);
  }

  private pushSingle(
    object: Object3D & { geometry?: BufferGeometry },
    material: Material,
    materialIndex: number,
    camera: Camera,
  ): void {
    if (!material.visible) return;
    const transparent = material.transparent && material.blending !== 'none';
    const sphere = (object as unknown as { boundingSphere?: Sphere | null }).boundingSphere;
    let z = 0;
    if (sphere) {
      _worldCenter.copy(sphere.center).applyMatrix4(object.matrixWorld);
      z = _worldCenter.distanceToSquared(
        this.cameraPosition.setFromMatrixPosition(camera.matrixWorld),
      );
    } else {
      this.cameraPosition.setFromMatrixPosition(camera.matrixWorld);
      z = object.matrixWorld.elements[14] - this.cameraPosition.z;
    }
    this.renderList.push({
      object: object as never,
      material,
      materialIndex,
      transparent,
      z,
      order: object.renderOrder,
    });
  }

  // ------------------------------------------------------------ uniforms ---

  /**
   * Uploads `FrameUniforms` once per frame.
   *
   * The camera's own matrices are copied into scratch buffers and remapped to
   * WebGPU clip space (`z' = z*0.5 + w*0.5`) here 閳?never in place.
   */
  private uploadFrameUniforms(scene: Scene, camera: Camera): void {
    writeClipSpaceRemap(this.gpuProjection, camera.projectionMatrix);
    writeViewProjection(this.gpuViewProjection, camera.projectionMatrix, camera.matrixWorldInverse);
    this.cameraPosition.setFromMatrixPosition(camera.matrixWorld);

    packFrameUniforms(this.frameData, {
      projectionMatrix: { elements: this.gpuProjection },
      viewMatrix: camera.matrixWorldInverse,
      viewProjectionMatrix: { elements: this.gpuViewProjection },
      cameraPosition: this.cameraPosition,
      lightState: this.lightState,
      fog: scene.fog ?? null,
    });
    safeWriteBuffer(this.device.queue, this.frameBuffer, 0, this.frameData, 0, FRAME_UNIFORM_BYTES);
  }

  // --------------------------------------------------------------- draw ----

  /** True when the draw was actually issued. */
  private drawItem(pass: GPURenderPassEncoder, item: RenderItem, _camera: Camera): boolean {
    void _camera;
    const material = item.material;
    const geometry = item.object.geometry as BufferGeometry;
    const record = this.geometries.prepare(geometry);
    const request = this.pipelineRequest(material, geometry, record);
    if (!request) return false;

    const key = this.pipelines.keyFor(request);
    const pipeline = this.pipelines.get(key) ?? this.pipelines.request(request);
    if (!pipeline) return false;

    const uniform = this.pipelines.uploadObjectUniforms(material, item.object, this.textures);

    pass.setPipeline(pipeline);
    pass.setBindGroup(0, this.frameBindGroup);
    pass.setBindGroup(1, uniform.bindGroup);

    let slot = 0;
    for (const name of PIPELINE_ATTRIBUTES) {
      const attribute = record.attributes.get(name);
      if (!attribute) continue;
      pass.setVertexBuffer(slot, attribute.buffer);
      slot++;
    }

    const plan = planDraw(
      geometry,
      this.geometries,
      record,
      item.materialIndex,
      Array.isArray(item.object.material),
    );
    if (plan.indexBuffer) pass.setIndexBuffer(plan.indexBuffer, plan.indexFormat);

    const [primitiveUnit, primitiveSize] = primitiveStats(plan.drawMode);
    for (const range of plan.ranges) {
      if (range.count <= 0) continue;
      if (plan.indexBuffer) {
        pass.drawIndexed(range.count, 1, range.start, 0);
      } else {
        pass.draw(range.count, 1, range.start, 0);
      }
      this.accumulateInfo(primitiveUnit, primitiveSize, range.count);
    }

    this.info.render.calls++;
    return true;
  }

  /** Builds the pipeline request (shader name, topology, vertex layout). */
  private pipelineRequest(
    material: Material,
    geometry: BufferGeometry,
    record: WgpuGeometryRecord,
  ): WgpuPipelineRequest | null {
    if (record.attributes.size === 0) return null;
    const drawMode = (geometry.drawMode ?? 'triangles') as DrawMode;
    const topology = TOPOLOGY_FOR_DRAW_MODE[drawMode] ?? 'triangle-list';
    const indexed = planUsesIndex(geometry, topology);
    const indexFormat: GPUIndexFormat | null =
      indexed && geometry.index
        ? geometry.index.array instanceof Uint32Array
          ? 'uint32'
          : 'uint16'
        : topology === 'point-list' || drawMode === 'line-strip'
          ? 'uint32'
          : null;
    return {
      material,
      indexFormat,
      topology,
      vertexLayoutKey: `${vertexLayoutKey(record.attributes)}|${indexFormat ?? 'none'}`,
      vertexLayouts: vertexBufferLayouts(record.attributes),
    };
  }

  private accumulateInfo(primitiveUnit: number, primitiveSize: number, count: number): void {
    if (primitiveUnit === 1 && primitiveSize === 3) this.info.render.triangles += count / 3;
    else if (primitiveUnit === 1 && primitiveSize === 1) this.info.render.points += count;
    else if (primitiveUnit === 2) this.info.render.lines += Math.floor(count / 2);
  }

  // ---------------------------------------------------------- background ---

  private drawBackgroundTexture(pass: GPURenderPassEncoder, texture: Texture): void {
    const pipeline = this.pipelines.backgroundPipeline;
    if (!pipeline) return;
    const record = this.textures.upload(texture);
    const bindGroup = this.pipelines.backgroundBindGroup(
      record.view ?? record.texture.createView(),
    );
    pass.setPipeline(pipeline);
    pass.setBindGroup(0, bindGroup);
    pass.setVertexBuffer(0, this.pipelines.backgroundBuffer);
    pass.draw(4, 1, 0, 0);
    this.info.render.calls++;
  }

  // ---------------------------------------------------------------- misc ---

  /** Uploads a texture eagerly so the first draw does not stall. */
  initTexture(texture: Texture): void {
    this.textures.upload(texture);
  }

  /** Uploads a geometry eagerly. */
  initGeometry(geometry: BufferGeometry): void {
    this.geometries.prepare(geometry);
  }

  resetInfo(): void {
    this.info.render.calls = 0;
    this.info.render.triangles = 0;
    this.info.render.lines = 0;
    this.info.render.points = 0;
    this.info.render.time = 0;
  }

  estimateMemoryUsage(): number {
    return this.geometries.bytes + this.textures.bytes + FRAME_UNIFORM_BYTES;
  }

  private watchDeviceLost(): void {
    void this.device.lost.then((detail) => {
      this.deviceLost = true;
      if (this.disposed) return;
      console.error(
        `mini3d.WebGPURenderer: GPUDevice was lost (reason: ${detail.reason || 'unknown'}): ` +
          `${detail.message || 'no further information'}`,
      );
    });
  }

  dispose(): void {
    if (this.disposed) return;
    this.disposed = true;
    this.geometries.dispose();
    this.textures.dispose();
    this.pipelines.dispose();
    this.frameBuffer.destroy();
    this.depthTexture?.destroy();
    this.depthTexture = null;
    this.depthView = null;
    try {
      this.context.unconfigure();
    } catch {
      /* already unconfigured */
    }
  }
}

// -------------------------------------------------------------- helpers ----

/**
 * The format a context was configured with. `getConfiguration()` may throw in
 * implementations that predate the method, and a hand-rolled `GPUCanvasContext`
 * (headless test doubles) may not have it at all.
 */
function configuredFormat(context: GPUCanvasContext): GPUTextureFormat | null {
  try {
    const getConfiguration = (context as unknown as {
      getConfiguration?: () => GPUCanvasConfiguration;
    }).getConfiguration;
    return getConfiguration ? getConfiguration.call(context).format : null;
  } catch {
    return null;
  }
}

/** `true` when the geometry's own index buffer can drive the draw directly. */
function planUsesIndex(geometry: BufferGeometry, topology: GPUPrimitiveTopology): boolean {
  if (topology === 'line-strip' || topology === 'point-list') return false;
  return topologySupportsIndexed(topology) && geometry.index !== null;
}

/** A single `pass.draw*` range plus how the draw must index. */
interface DrawPlan {
  indexBuffer: GPUBuffer | null;
  indexFormat: GPUIndexFormat;
  ranges: { start: number; count: number }[];
  drawMode: DrawMode;
}

/**
 * Resolves how one geometry is drawn, including the index-buffer expansion for
 * the topologies WebGPU cannot index (see the file header):
 *
 * - `'line-strip'` (used by `LineLoop`) becomes a `line-list` over the
 *   generated `0,1, 1,2, 閳ヮ泦 index buffer.
 * - an indexed point cloud becomes a `point-list` over an identity index.
 *
 * Both expansions are cached per source-index version by `WgpuGeometries`.
 */
function planDraw(
  geometry: BufferGeometry,
  cache: WgpuGeometries,
  record: WgpuGeometryRecord,
  materialIndex: number,
  multiMaterial: boolean,
): DrawPlan {
  const drawMode = (geometry.drawMode ?? 'triangles') as DrawMode;
  const topology = TOPOLOGY_FOR_DRAW_MODE[drawMode] ?? 'triangle-list';
  const index = geometry.index;
  const drawStart = Math.max(geometry.drawRange.start, 0);
  const total = geometry.drawCount;
  const drawEnd = Number.isFinite(geometry.drawRange.count)
    ? Math.min(total, drawStart + Math.max(0, geometry.drawRange.count))
    : total;

  const groups = geometry.groups;
  const hasGroups = groups.length > 0;
  const ranges: { start: number; count: number }[] = [];
  if (hasGroups && multiMaterial) {
    // Only the groups belonging to this item's material slot are drawn. A single
    // material covers every group, so that case falls through to one range.
    for (const group of groups) {
      if (group.materialIndex !== materialIndex) continue;
      if (group.count <= 0) continue;
      const start = Math.max(group.start, 0);
      const count = Math.min(group.count, total - start);
      if (count > 0) ranges.push({ start, count });
    }
  } else if (drawEnd > drawStart) {
    ranges.push({ start: drawStart, count: drawEnd - drawStart });
  }

  if (drawMode === 'line-strip') {
    // A strip cannot be indexed in WebGPU, so the whole (possibly grouped)
    // range is expanded once into a line list.
    const first = hasGroups ? (ranges[0]?.start ?? 0) : drawStart;
    const last = hasGroups
      ? (ranges[ranges.length - 1]?.start ?? 0) + (ranges[ranges.length - 1]?.count ?? 0)
      : drawEnd;
    const vertexCount = Math.max(2, last - first);
    const expansion = cache.lineStripIndex(geometry, vertexCount);
    if (!expansion) return emptyPlan(drawMode);
    const segments = expansion.count - 1;
    return {
      indexBuffer: expansion.buffer,
      indexFormat: 'uint32',
      ranges: segments > 0 ? [{ start: 0, count: segments * 2 }] : [],
      drawMode,
    };
  }

  if (topology === 'point-list' && index) {
    const expansion = cache.pointsIndex(geometry, index.count);
    if (!expansion) return emptyPlan(drawMode);
    return {
      indexBuffer: expansion.buffer,
      indexFormat: 'uint32',
      ranges: hasGroups ? ranges : [{ start: 0, count: expansion.count }],
      drawMode,
    };
  }

  if (topologySupportsIndexed(topology) && index && record.index) {
    return {
      indexBuffer: record.index.buffer,
      indexFormat: record.index.format,
      ranges,
      drawMode,
    };
  }

  return { indexBuffer: null, indexFormat: 'uint16', ranges, drawMode };
}

function emptyPlan(drawMode: DrawMode): DrawPlan {
  return { indexBuffer: null, indexFormat: 'uint16', ranges: [], drawMode };
}

function primitiveStats(drawMode: DrawMode): [number, number] {
  switch (drawMode) {
    case 'points':
      return [1, 1];
    case 'lines':
      return [2, 2];
    case 'line-strip':
      return [2, 1];
    case 'triangle-strip':
      return [1, 1];
    case 'triangles':
    default:
      return [1, 3];
  }
}

/**
 * Opaque first, then transparent back-to-front, with `renderOrder` applied within
 * each group. Matches `WebGLRenderer.compareRenderItems`; ordering by
 * `renderOrder` first would draw a transparent object before the opaque geometry
 * behind it and break the blend.
 */
function compareRenderItems(a: RenderItem, b: RenderItem): number {
  if (a.transparent !== b.transparent) return a.transparent ? 1 : -1;
  if (a.order !== b.order) return a.order - b.order;
  return a.transparent ? b.z - a.z : a.z - b.z;
}

function clampDimension(value: number, max: number): number {
  if (!Number.isFinite(value) || value <= 0) return 1;
  return Math.max(1, Math.min(Math.floor(value), max));
}

function now(): number {
  if (typeof performance !== 'undefined' && typeof performance.now === 'function') {
    return performance.now();
  }
  return Date.now();
}

// Module-level scratch objects keep per-frame allocation at zero.
const _worldCenter = new Vector3();
