export declare const PI: number;
export declare const TWO_PI: number;
export declare const PI_2: number;
export declare const PI_4: number;
export declare const PI_8: number;
export declare const RAD_TO_DEG: number;
export declare const DEG_TO_RAD: number;
export declare const radToDeg: (radian: number) => number;
export declare const degToRad: (deg: number) => number;
export declare const easingFuncs: {
    linear: (t: number) => number;
    easeInQuad: (t: number) => number;
    easeOutQuad: (t: number) => number;
    easeInOutQuad: (t: number) => number;
    easeInCubic: (t: number) => number;
    easeOutCubic: (t: number) => number;
    easeInOutCubic: (t: number) => number;
    easeInQuart: (t: number) => number;
    easeOutQuart: (t: number) => number;
    easeInOutQuart: (t: number) => number;
    easeInSine: (t: number) => number;
    easeOutSine: (t: number) => number;
    easeInOutSine: (t: number) => number;
    easeInExpo: (t: number) => number;
    easeOutExpo: (t: number) => number;
    easeInOutExpo: (t: number) => number;
    easeInCirc: (t: number) => number;
    easeOutCirc: (t: number) => number;
    easeInOutCirc: (t: number) => number;
    easeOutElastic: (t: number) => number;
    easeOutBack: (t: number) => number;
    easeOutBounce: (t: number) => number;
};
export declare const smoothStep: (a: number, b: number, x: number) => number;
export declare const mix: (a: number, b: number, c: number) => number;
export declare const interpolate: (a: number, b: number, t: number) => number;
export declare const clamp: (value: number, min: number, max: number) => number;
export declare const randomRange: (min: number, max: number) => number;
export declare const randomRangeInt: (min: number, max: number) => number;
export declare const equalsEpsilon: (a: number, b: number, epsilon?: number) => boolean;
export declare const equals: (a: number, b: number) => boolean;
