import { Matrix2DLike } from '../interface/IMatrix2D';
import { PointLike } from '../interface/IPoint';
import { IVector2D, Vector2DLike } from '../interface/IVector2D';
export declare const copy: (out: Vector2DLike, vector: Vector2DLike) => Vector2DLike;
export declare const subtract: (out: Vector2DLike, vector: Vector2DLike, vector2: Vector2DLike) => Vector2DLike;
export declare const add: (out: Vector2DLike, vector: Vector2DLike, vector2: Vector2DLike) => Vector2DLike;
export declare const multiply: (out: Vector2DLike, vector: Vector2DLike, vector2: Vector2DLike) => Vector2DLike;
export declare const divide: (out: Vector2DLike, vector: Vector2DLike, vector2: Vector2DLike) => Vector2DLike;
export declare const multiplyScalar: (out: Vector2DLike, vector: Vector2DLike, scale: number) => Vector2DLike;
export declare const divideScalar: (out: Vector2DLike, vector: Vector2DLike, scale: number) => Vector2DLike;
export declare const negate: (out: Vector2DLike, vector: Vector2DLike) => Vector2DLike;
export declare const magnitude: (vector: Vector2DLike) => number;
export declare const squareMagnitude: (vector: Vector2DLike) => number;
export declare const distanceTo: (vector: Vector2DLike, vector2: Vector2DLike) => number;
export declare const distanceToSquared: (vector: Vector2DLike, vector2: Vector2DLike) => number;
export declare const dot: (vector: Vector2DLike, vector2: Vector2DLike) => number;
export declare const cross: (vector: Vector2DLike, vector2: Vector2DLike) => number;
export declare const angleTo: (vector: Vector2DLike, vector2: Vector2DLike) => number;
export declare const angle: (vector: Vector2DLike) => number;
export declare const normalize: (out: Vector2DLike, vector: Vector2DLike) => Vector2DLike;
export declare const setLength: (out: Vector2DLike, vector: Vector2DLike, len: number) => boolean;
export declare const equals: (vector: Vector2DLike, vector2: Vector2DLike) => boolean;
export declare const equalsEpsilon: (vector: Vector2DLike, vector2: Vector2DLike, epsilon?: number) => boolean;
export declare const applyMatrix2D: (out: Vector2DLike, vector: Vector2DLike, matrix: Matrix2DLike) => Vector2DLike;
export declare const isZero: (vector: Vector2DLike) => boolean;
export declare const isOne: (vector: Vector2DLike) => boolean;
export declare const isFinite: (vector: Vector2DLike) => boolean;
export declare const fromAngle: (out: Vector2DLike, angle: number, len: number) => Vector2DLike;
export declare const from: (out: Vector2DLike, vector: Vector2DLike) => Vector2DLike;
export declare const fromValues: (out: Vector2DLike, x: number, y: number) => Vector2DLike;
export declare const fromPoint: (out: Vector2DLike, point: PointLike) => Vector2DLike;
export declare class Vector2D extends Float32Array implements IVector2D {
    static ZERO: Vector2D;
    static ONE: Vector2D;
    static fromRotation(radian: number): Vector2D;
    static fromPoint(point: PointLike): Vector2D;
    static fromValues(x: number, y: number): Vector2D;
    clone(): IVector2D;
    copy(vector: Vector2DLike): IVector2D;
    add(vector: Vector2DLike): IVector2D;
    subtract(vector: Vector2DLike): IVector2D;
    multiply(vector: Vector2DLike): IVector2D;
    divide(vector: Vector2DLike): IVector2D;
    negate(): IVector2D;
    normalize(): IVector2D;
    dot(vector: Vector2DLike): number;
    cross(vector: Vector2DLike): number;
    magnitude(): number;
    squareMagnitude(): number;
    distanceTo(vector: Vector2DLike): number;
    distanceToSquared(vector: Vector2DLike): number;
    angleTo(vector: Vector2DLike): number;
    angle(): number;
    applyMatrix2D(matrix: Matrix2DLike): IVector2D;
    equals(vector: Vector2DLike): boolean;
    equalsEpsilon(vector: Vector2DLike, epsilon: number): boolean;
}
