export declare const CanvasDefaultStyle: {
    readonly direction: "ltr";
    readonly fillStyle: "#000000";
    readonly filter: "none";
    readonly font: "10px sans-serif";
    readonly fontKerning: "auto";
    readonly fontStretch: "normal";
    readonly fontVariantCaps: "normal";
    readonly globalAlpha: 1;
    readonly globalCompositeOperation: "source-over";
    readonly imageSmoothingEnabled: true;
    readonly imageSmoothingQuality: "low";
    readonly lang: "inherit";
    readonly letterSpacing: "0px";
    readonly lineCap: "butt";
    readonly lineDashOffset: 0;
    readonly lineJoin: "miter";
    readonly lineWidth: 1;
    readonly miterLimit: 10;
    readonly shadowBlur: 0;
    readonly shadowColor: "rgba(0, 0, 0, 0)";
    readonly shadowOffsetX: 0;
    readonly shadowOffsetY: 0;
    readonly strokeStyle: "#000000";
    readonly textAlign: "start";
    readonly textBaseline: "alphabetic";
    readonly textRendering: "auto";
    readonly wordSpacing: "0px";
    readonly lineDash: number[];
};
export declare function resetCanvasDefaultStyle(ctx: any): void;
