import { BufferGeometry } from '../core/BufferGeometry';

/**
 * Axis index used by the face builder: `0 = x`, `1 = y`, `2 = z`.
 * Kept as a small union so the scratch-vector indexing stays type safe.
 */
type Axis = 0 | 1 | 2;

/**
 * Box topology: six axis-aligned quad grids (`+x`, `-x`, `+y`, `-y`, `+z`, `-z`),
 * each generated by the same plane builder. Every face owns its `(gridX + 1) *
 * (gridY + 1)` vertices — they are shared *within* a face (indexed quads, each
 * split into two counter-clockwise triangles) but never across faces, because
 * the normal and the UV of a corner differ per face. Each face is emitted as one
 * draw group so a mesh can bind six materials, exactly like three.js.
 *
 * UVs are a per-face 0..1 quad; the `udir`/`vdir` signs of the six face calls
 * are chosen so that the texture is never mirrored.
 */
export class BoxGeometry extends BufferGeometry {
  parameters: {
    width: number;
    height: number;
    depth: number;
    widthSegments: number;
    heightSegments: number;
    depthSegments: number;
  };

  constructor(
    width = 1,
    height = 1,
    depth = 1,
    widthSegments = 1,
    heightSegments = 1,
    depthSegments = 1,
  ) {
    super();
    this.name = 'BoxGeometry';
    this.parameters = { width, height, depth, widthSegments, heightSegments, depthSegments };

    // Clamp degenerate counts so the segment sizes never divide by zero.
    const gridX = Math.max(1, Math.floor(widthSegments));
    const gridY = Math.max(1, Math.floor(heightSegments));
    const gridZ = Math.max(1, Math.floor(depthSegments));

    const positions: number[] = [];
    const normals: number[] = [];
    const uvs: number[] = [];
    const indices: number[] = [];

    // [u, v, w, uDir, vDir, faceWidth, faceHeight, faceDepth, gridU, gridV]
    const faces: Array<[Axis, Axis, Axis, number, number, number, number, number, number, number]> = [
      [2, 1, 0, -1, -1, depth, height, width, gridZ, gridY], // +x
      [2, 1, 0, 1, -1, depth, height, -width, gridZ, gridY], // -x
      [0, 2, 1, 1, 1, width, depth, height, gridX, gridZ], // +y
      [0, 2, 1, 1, -1, width, depth, -height, gridX, gridZ], // -y
      [0, 1, 2, 1, -1, width, height, depth, gridX, gridY], // +z
      [0, 1, 2, -1, -1, width, height, -depth, gridX, gridY], // -z
    ];

    let groupStart = 0;
    for (let i = 0; i < faces.length; i++) {
      const [u, v, w, uDir, vDir, faceWidth, faceHeight, faceDepth, gridU, gridV] = faces[i];
      buildPlane(
        u,
        v,
        w,
        uDir,
        vDir,
        faceWidth,
        faceHeight,
        faceDepth,
        gridU,
        gridV,
        positions,
        normals,
        uvs,
        indices,
      );
      const groupCount = gridU * gridV * 6;
      this.addGroup(groupStart, groupCount, i);
      groupStart += groupCount;
    }

    this.setPosition(positions);
    this.setNormal(normals);
    this.setUv(uvs);
    this.setIndex(indices);
  }
}

/**
 * Generates one face of the box as a `gridX * gridY` quad grid placed on the
 * plane `w = depth / 2`. Mirrors three.js's `buildPlane`: `u`/`v` are the two
 * in-plane axes, `w` is the face axis, and the signs plus the (possibly
 * negative) width/height/depth flip the parameterisation so the resulting
 * triangles are counter-clockwise when seen from outside the box.
 */
function buildPlane(
  u: Axis,
  v: Axis,
  w: Axis,
  uDir: number,
  vDir: number,
  width: number,
  height: number,
  depth: number,
  gridX: number,
  gridY: number,
  positions: number[],
  normals: number[],
  uvs: number[],
  indices: number[],
): void {
  const segmentWidth = width / gridX;
  const segmentHeight = height / gridY;
  const widthHalf = width / 2;
  const heightHalf = height / 2;
  const depthHalf = depth / 2;
  const gridX1 = gridX + 1;
  const gridY1 = gridY + 1;

  // First vertex produced by this face; indices are relative to it.
  const offset = positions.length / 3;
  const vector: [number, number, number] = [0, 0, 0];

  // Vertices, normals and UVs: one vertex per grid intersection.
  for (let iy = 0; iy < gridY1; iy++) {
    const y = iy * segmentHeight - heightHalf;
    for (let ix = 0; ix < gridX1; ix++) {
      const x = ix * segmentWidth - widthHalf;

      vector[u] = x * uDir;
      vector[v] = y * vDir;
      vector[w] = depthHalf;
      positions.push(vector[0], vector[1], vector[2]);

      vector[u] = 0;
      vector[v] = 0;
      vector[w] = depth > 0 ? 1 : -1;
      normals.push(vector[0], vector[1], vector[2]);

      uvs.push(ix / gridX, 1 - iy / gridY);
    }
  }

  // Indices: two counter-clockwise triangles per quad.
  for (let iy = 0; iy < gridY; iy++) {
    for (let ix = 0; ix < gridX; ix++) {
      const a = offset + ix + gridX1 * iy;
      const b = offset + ix + gridX1 * (iy + 1);
      const c = offset + ix + 1 + gridX1 * (iy + 1);
      const d = offset + ix + 1 + gridX1 * iy;
      indices.push(a, b, d, b, c, d);
    }
  }
}
