import { default as camelCase } from './camelCase';
import { default as capitalize } from './capitalize';
import { default as deburr } from './deburr';
import { default as endsWith } from './endsWith';
import { default as escape } from './escape';
import { default as escapeRegExp } from './escapeRegExp';
import { default as kebabCase } from './kebabCase';
import { default as lowerCase } from './lowerCase';
import { default as lowerFirst } from './lowerFirst';
import { default as pad } from './pad';
import { default as padEnd } from './padEnd';
import { default as padStart } from './padStart';
import { default as parseInt } from './parseInt';
import { default as repeat } from './repeat';
import { default as replace } from './replace';
import { default as snakeCase } from './snakeCase';
import { default as split } from './split';
import { default as startCase } from './startCase';
import { default as startsWith } from './startsWith';
import { default as template } from './template';
import { default as templateSettings } from './templateSettings';
import { default as toLower } from './toLower';
import { default as toUpper } from './toUpper';
import { default as trim } from './trim';
import { default as trimEnd } from './trimEnd';
import { default as trimStart } from './trimStart';
import { default as truncate } from './truncate';
import { default as unescape } from './unescape';
import { default as upperCase } from './upperCase';
import { default as upperFirst } from './upperFirst';
import { default as words } from './words';
declare const defaultExport: {
    camelCase: typeof camelCase;
    capitalize: typeof capitalize;
    deburr: typeof deburr;
    endsWith: typeof endsWith;
    escape: typeof escape;
    escapeRegExp: typeof escapeRegExp;
    kebabCase: typeof kebabCase;
    lowerCase: typeof lowerCase;
    lowerFirst: typeof lowerFirst;
    pad: typeof pad;
    padEnd: typeof padEnd;
    padStart: typeof padStart;
    parseInt: typeof parseInt;
    repeat: typeof repeat;
    replace: typeof replace;
    snakeCase: typeof snakeCase;
    split: typeof split;
    startCase: typeof startCase;
    startsWith: typeof startsWith;
    template: typeof template;
    templateSettings: typeof templateSettings;
    toLower: typeof toLower;
    toUpper: typeof toUpper;
    trim: typeof trim;
    trimEnd: typeof trimEnd;
    trimStart: typeof trimStart;
    truncate: typeof truncate;
    unescape: typeof unescape;
    upperCase: typeof upperCase;
    upperFirst: typeof upperFirst;
    words: typeof words;
};
export default defaultExport;
