import { EventEmitter } from '../../events/EventEmitter';
import { PointerEventSystem, PointerEventsMaps } from '../../events/PointerEventSystem';
import { Transform } from '../../math/Transform';
import { ShapePath } from '../../math/ShapePath';
import { CanvasTextMeasure } from '../../math/Paragraph';
import { BoundingRect } from '../../math/BoundingRect';
type CanvasRendererProps = {
    dpr?: number;
    canvas?: HTMLCanvasElement;
    width: number;
    height: number;
};
type IRenderObjectStyle = {
    fillStyle?: string | CanvasGradient | CanvasPattern;
    fillRule?: CanvasFillRule;
    strokeStyle?: string | CanvasGradient | CanvasPattern;
    globalAlpha?: number;
    globalCompositeOperation?: GlobalCompositeOperation;
    clipPath?: Path2D;
    clipObj?: IRenderObject<keyof RenderObjectShape>;
    lineWidth?: number;
    lineCap?: CanvasLineCap;
    lineJoin?: CanvasLineJoin;
    lineDash?: number[];
    lineDashOffset?: number;
    miterLimit?: number;
    shadowBlur?: number;
    shadowColor?: string;
    shadowOffsetX?: number;
    shadowOffsetY?: number;
    fontSize?: number;
    fontFamily?: string;
    fontStyle?: 'normal' | 'italic';
    fontWeight?: number | 'bold' | 'normal';
    fontStretch?: CanvasFontStretch;
    fontKerning?: CanvasFontKerning;
    fontVariant?: CanvasFontVariantCaps;
    lineHeight?: number;
    letterSpacing?: number;
    wordSpacing?: number;
    textBaseline?: CanvasTextBaseline;
    textAlign?: CanvasTextAlign;
};
type RenderObjectShape = {
    image: {
        src?: string;
        image?: CanvasImageSource;
        width?: number;
        height?: number;
    };
    group: {
        remove?(obj: IRenderObject<keyof RenderObjectShape>): void;
        add?<K extends keyof RenderObjectShape>(type: K, config: IRenderObject<K>): IRenderObject<K>;
    };
    text: {
        text: string;
    };
    rect: {
        width: number;
        height: number;
    };
    circle: {
        radius: number;
        startAngle: number;
        endAngle: number;
        clockwise?: boolean;
    };
    ellipse: {
        rx: number;
        ry: number;
        xrotation?: number;
        startAngle: number;
        endAngle: number;
        clockwise?: boolean;
    };
    path: {
        path?: ShapePath;
    };
    line: {
        x1: number;
        y1: number;
        x2: number;
        y2: number;
    };
    shape: {};
};
type IRenderObject<T extends keyof RenderObjectShape> = {
    owner?: CanvasRenderer;
    parent?: IRenderObject<keyof RenderObjectShape>;
    type?: T;
    id?: string;
    firstFill?: boolean;
    draggable?: boolean;
    cursor?: string;
    visible?: boolean;
    silent?: boolean;
    style?: IRenderObjectStyle;
    position?: {
        x: number;
        y: number;
    };
    scale?: {
        x: number;
        y: number;
    };
    origin?: {
        x: number;
        y: number;
    };
    rotation?: number;
    scaleStroke?: boolean;
    transform?: Transform;
    bounds?: BoundingRect;
    path?: ShapePath;
    children?: IRenderObject<keyof RenderObjectShape>[];
    event?: EventEmitter<CanvasRendererEvents>;
    onUpdate?: () => void;
    beforeDraw?: (ctx: CanvasRenderingContext2D) => void;
    afterDraw?: (ctx: CanvasRenderingContext2D) => void;
    draw?: (ctx: CanvasRenderingContext2D) => void;
    dirty?: () => void;
    updatePath?: () => void;
    hitTest?: (x: number, y: number) => boolean;
    [K: string]: any;
} & RenderObjectShape[T];
type CanvasRendererEvents = {
    'render:before': [renderer: CanvasRenderer];
    'render:after': [renderer: CanvasRenderer];
    tick: [delta: number];
} & PointerEventsMaps;
declare function createOffscreenCanvas(width: number, height: number, dpr: number): HTMLCanvasElement | OffscreenCanvas;
export declare class CanvasRenderer extends EventEmitter<CanvasRendererEvents> {
    static createOffscreenCanvas: typeof createOffscreenCanvas;
    domElement: HTMLCanvasElement;
    ctx: CanvasRenderingContext2D;
    dpr: number;
    width: number;
    height: number;
    objects: IRenderObject<keyof RenderObjectShape>[];
    pointerEventSystem: PointerEventSystem;
    _rect: DOMRect;
    _textMeasure: CanvasTextMeasure;
    objUid: number;
    animationRef: number;
    constructor(props: CanvasRendererProps);
    start(): void;
    stop(): void;
    initInteraction(): void;
    setSize(width: number, height: number, updateStyle?: boolean): void;
    save(): void;
    translate(x: number, y: number): void;
    scale(x: number, y: number): void;
    rotate(angle: number): void;
    transform(a: number, b: number, c: number, d: number, e: number, f: number): void;
    setTransform(a: number, b: number, c: number, d: number, e: number, f: number): void;
    resetTransform(): void;
    getTransform(): DOMMatrix;
    fill(fillRule?: CanvasFillRule): void;
    fill(path?: globalThis.Path2D, fillRule?: CanvasFillRule): void;
    stroke(path?: globalThis.Path2D): void;
    fillText(text: string, x: number, y: number): void;
    strokeText(text: string, x: number, y: number): void;
    setFillStyle(fillStyle: string | CanvasGradient | CanvasPattern): void;
    setStrokeStyle(strokeStyle: string | CanvasGradient | CanvasPattern): void;
    setLineWidth(lineWidth: number): void;
    setLineCap(lineCap: CanvasLineCap): void;
    setLineJoin(lineJoin: CanvasLineJoin): void;
    setLineDash(lineDash: number[]): void;
    setLineDashOffset(lineDashOffset: number): void;
    setGlobalAlpha(alpha: number): void;
    setGlobalCompositeOperation(operation: GlobalCompositeOperation): void;
    setMiterLimit(miterLimit: number): void;
    setShadowBlur(blur: number): void;
    setShadowColor(color: string): void;
    setShadowOffsetX(x: number): void;
    setShadowOffsetY(y: number): void;
    setFont(font: string): void;
    setFontStretch(stretch: CanvasFontStretch): void;
    setFontVariant(fontKerning: CanvasFontKerning): void;
    setFontVariantCaps(fontVariantCaps: CanvasFontVariantCaps): void;
    setTextAlign(align: CanvasTextAlign): void;
    setBaseline(baseline: CanvasTextBaseline): void;
    measureText(text: string): TextMetrics;
    restore(): void;
    clearRect(): void;
    setObjectStrokePath(obj: IRenderObject<keyof RenderObjectShape>): void;
    addObject<K extends keyof RenderObjectShape>(type: K, config: IRenderObject<K>): IRenderObject<K>;
    add<K extends keyof RenderObjectShape>(type: K, config: IRenderObject<K>): IRenderObject<K>;
    remove(config: IRenderObject<keyof RenderObjectShape>): void;
    getBounds(obj: IRenderObject<keyof RenderObjectShape>): BoundingRect;
    hitTestObject(obj: IRenderObject<keyof RenderObjectShape>, x: number, y: number): boolean;
    findHover(x: number, y: number): IRenderObject<keyof RenderObjectShape>;
    rect(x: number, y: number, width: number, height: number): void;
    arc(x: number, y: number, radius: number, startAngle: number, endAngle: number, counterclockwise?: boolean): void;
    ellipse(x: number, y: number, radiusX: number, radiusY: number, rotation: number, startAngle: number, endAngle: number, counterclockwise?: boolean): void;
    lineTo(x: number, y: number): void;
    moveTo(x: number, y: number): void;
    bezierCurveTo(x1: number, y1: number, x2: number, y2: number, x3: number, y3: number): void;
    quadraticCurveTo(x1: number, y1: number, x2: number, y2: number): void;
    beginPath(): void;
    closePath(): void;
    buildShapePath(ctx: CanvasRenderingContext2D | Path2D | ShapePath, obj: IRenderObject<keyof RenderObjectShape>): void;
    getFontString(style: IRenderObjectStyle): string;
    applyObjectStyle(obj: IRenderObject<keyof RenderObjectShape>): void;
    renderFillText(obj: IRenderObject<'text'>): void;
    renderStrokeText(obj: IRenderObject<'text'>): void;
    renderFillObject(obj: IRenderObject<keyof RenderObjectShape>): void;
    renderStrokeObject(obj: IRenderObject<keyof RenderObjectShape>): void;
    renderObject(obj: IRenderObject<keyof RenderObjectShape>): void;
    _getBatchKey(obj: IRenderObject<keyof RenderObjectShape>): string | null;
    batchRenderObjects(objects: IRenderObject<keyof RenderObjectShape>[]): void;
    renderObjects(objects: IRenderObject<keyof RenderObjectShape>[]): void;
    render(): void;
    private needUpdate;
    private delta;
    private lastTime;
    refresh(): void;
    private tick;
}
export {};
