import { EventEmitter } from '../events/EventEmitter';
import { PathBuilder } from '../math/PathBuilder';
import { BlendOperation, FillRule, FillStyle, FontStyles, LineCap, LineJoin, Paint, TextAlign, TextBaseline } from './Paint';
import { Matrix2D } from '../math/Matrix2D';
import { ColorInput, ColorValue } from '../math/Color';
import { ConicGradient, LinearGradient, RadialGradient } from '../math/Gradient';
import { Pattern } from '../math/Pattern';
export type RendererEvents = {
    resize: [renderer: Renderer];
};
export interface RendererConstructor {
    new (): Renderer;
}
export type RendererProps = {
    canvas?: HTMLCanvasElement | SVGElement;
    width: number;
    height: number;
    dpr: number;
};
export type RenderOptions = {};
export declare abstract class Renderer extends EventEmitter<RendererEvents> {
    renderType: string;
    width: number;
    height: number;
    deviceWidth: number;
    deviceHeight: number;
    dpr: number;
    clearColorValue: ColorValue;
    _matrix: Matrix2D;
    abstract domElement: HTMLElement;
    constructor();
    init(options: Partial<RendererProps>): Promise<void>;
    abstract initContext(options: Partial<RendererProps>): Promise<void>;
    setDpr(dpr: number): void;
    updateSize(updateStyle?: boolean): void;
    setSize(width: number, height: number, dpr?: number): void;
    clearColor(color: ColorInput): void;
    createLinearGradient(x1: number, y1: number, x2: number, y2: number): LinearGradient;
    createRadialGradient(x: number, y: number, r: number, xCenter: number, yCenter: number, rCenter: number): RadialGradient;
    createConicGradient(startAngle: number, x: number, y: number): ConicGradient;
    createPattern(): Pattern;
    abstract transform(a: number, b: number, c: number, d: number, e: number, f: number): void;
    abstract setTransform(a: number, b: number, c: number, d: number, e: number, f: number): void;
    abstract getTransform(): Matrix2D;
    abstract resetTransform(): void;
    abstract translate(x: number, y: number): void;
    abstract scale(sx: number, sy: number): void;
    abstract rotate(angle: number): void;
    abstract clear(): void;
    abstract save(): void;
    abstract restore(): void;
    abstract beginPath(): void;
    abstract closePath(): void;
    abstract moveTo(x: number, y: number): void;
    abstract lineTo(x: number, y: number): void;
    abstract arcTo(x1: number, y1: number, x2: number, y2: number, radius: number): void;
    abstract quadraticCurveTo(x1: number, y1: number, x2: number, y2: number): void;
    abstract bezierCurveTo(x1: number, y1: number, x2: number, y2: number, x3: number, y3: number): void;
    abstract rect(x: number, y: number, width: number, height: number): void;
    abstract roundRect(x: number, y: number, width: number, height: number, radius: number | number[]): void;
    abstract arc(x: number, y: number, radius: number, startAngle: number, endAngle: number, ccw: boolean): void;
    abstract ellipse(x: number, y: number, radiusX: number, radiusY: number, rotation: number, startAngle: number, endAngle: number, ccw: boolean): void;
    abstract setGlobalAlpha(alpha: number): void;
    abstract setBlend(operation: BlendOperation): void;
    abstract setLineWidth(width: number): void;
    abstract setLineJoin(lineJoin: LineJoin): void;
    abstract setLineCap(lineCap: LineCap): void;
    abstract setLineDash(lineDash: number[]): void;
    abstract setLineDashOffset(lineDashOffset: number): void;
    abstract setMiterLimit(miterLimit: number): void;
    abstract setFillStyle(fillStyle: FillStyle): void;
    abstract setStrokeStyle(fillStyle: FillStyle): void;
    abstract setShadowColor(shadowColor: ColorInput): void;
    abstract setShadowOffsetX(shadowOffsetX: number): void;
    abstract setShadowOffsetY(shadowOffsetY: number): void;
    abstract setShadowBlur(shadowBlur: number): void;
    abstract setTextBaseline(textBaseline: TextBaseline): void;
    abstract setTextAlign(textAlign: TextAlign): void;
    abstract setWordSpacing(wordSpacing: number): void;
    abstract setLetterSpacing(letterSpacing: number): void;
    abstract setFont(style: Partial<FontStyles>): void;
    abstract fill(fillRule: FillRule): void;
    abstract stroke(): void;
    abstract fillText(text: string, x: number, y: number): void;
    abstract drawRect(x: number, y: number, width: number, height: number, paint: Paint): void;
    abstract drawCircle(x: number, y: number, radius: number, paint: Paint): void;
    abstract drawRoundRect(x: number, y: number, width: number, height: number, radius: number | number[], paint: Paint): void;
    abstract drawEllipse(x: number, y: number, radiusX: number, radiusY: number, paint: Paint): void;
    abstract drawPath(path: PathBuilder, paint: Paint): void;
    abstract drawImage(image: CanvasImageSource, x: number, y: number, w: number, h: number): void;
    abstract render(renderOptions: RenderOptions): void;
}
