import { Angle } from './angle';
import { Arc, Sector } from './arc';
import { Circle } from './circle';
import { Ellipse } from './ellipse';
import { Line, Ray, Segment } from './line';
import { Point } from './point';
import { Polygon, Polyline } from './polygon';
import { Rectangle } from './rectangle';
import { GeoElement } from './utilities';
export declare function isPolygonLike(shape: GeoElement): shape is Polygon | Rectangle;
export declare function isPolygon(shape: GeoElement): shape is Polygon;
export declare function isPolyline(shape: GeoElement): shape is Polyline;
export declare function isRectangle(shape: GeoElement): shape is Rectangle;
export declare function isLineLike(shape: GeoElement): shape is Line | Ray | Segment;
export declare function isLine(shape: GeoElement): shape is Line;
export declare function isRay(shape: GeoElement): shape is Ray;
export declare function isSegment(shape: GeoElement): shape is Segment;
export declare function isCircle(shape: GeoElement): shape is Circle;
export declare function isEllipse(shape: GeoElement): shape is Ellipse;
export declare function isArc(shape: GeoElement): shape is Arc;
export declare function isSector(shape: GeoElement): shape is Sector;
export declare function isAngle(shape: GeoElement): shape is Angle;
export declare function isPoint(shape: GeoElement): shape is Point;
