import { FabricObject } from '../shapes/Object/Object';
import { TFiller } from '../typedefs';
import { FabricText } from '../shapes/Text/Text';
import { Pattern } from '../Pattern';
import { Path } from '../shapes/Path';
import { ActiveSelection } from '../shapes/ActiveSelection';
export declare const isFiller: (filler: TFiller | string | null) => filler is TFiller;
export declare const isSerializableFiller: (filler: TFiller | string | null) => filler is TFiller;
export declare const isPattern: (filler: TFiller) => filler is Pattern;
export declare const isTextObject: (fabricObject?: FabricObject) => fabricObject is FabricText;
export declare const isPath: (fabricObject?: FabricObject) => fabricObject is Path;
export declare const isActiveSelection: (fabricObject?: FabricObject) => fabricObject is ActiveSelection;
