import { Transform } from '../../../../../../../src/math/Transform';
import { BoundingRect } from '../../../../../../../src/math/BoundingRect';
import { NodeOptions, NodeEvents } from '../../../../../../../src/types/Node';
import { CKEngine } from '../../../../../../../src/core/CKEngine';
export declare abstract class Node<Options extends NodeOptions = NodeOptions, E extends NodeEvents = NodeEvents> extends Transform<Options, E> {
    static uid: number;
    type: string;
    uid: number;
    effectFlag: number;
    props: Options;
    parent: Node<Options, E> | null;
    children: Node<Options, E>[] | null;
    _owner: CKEngine;
    _bounds: BoundingRect;
    _globalBounds: BoundingRect;
    constructor(options?: Options);
    updateTransform(): void;
    getDefaultProps(): Options[];
    get zIndex(): number;
    set zIndex(zIndex: number);
    get visible(): boolean;
    set visible(v: boolean);
    get ingore(): boolean;
    set ingore(v: boolean);
    get owner(): CKEngine;
    getChildEffectFlag(): number;
    getAllEffectFlag(): number;
    shouldRender(): boolean;
    shouldInteraction(): boolean;
    shouldAddToPendingRenderList(): boolean;
    get bounds(): BoundingRect;
    get globalBounds(): BoundingRect;
    isInViewport(viewport: BoundingRect): boolean;
    shouldUpdateGloablBounds(): number;
    shouldUpdateBounds(): number;
    getGlobalBounds(forceUpdate?: boolean): BoundingRect;
    getBounds(forceUpdate?: boolean): BoundingRect;
    abstract innerCalcBounds(): void;
    index(): number;
    insertBefore(child: Node<Options, E>, refChild?: Node<Options, E>): void;
    add(child: Node<Options, E>): void;
    removeSelf(): void;
    remove(child: Node<Options, E>): void;
    removeAllChildren(): void;
    traverse<T extends Node<Options, E>>(fn: (el: T) => void): void;
    traverseBackward<T extends Node<Options, E>>(fn: (el: T) => void): void;
    onBeforeUpdate(delta: number): void;
    onUpdate(delta: number): void;
    onAfterUpdate(delta: number): void;
    dispose(): void;
}
