import { RotValue } from './Rot';
import { TransformValue } from './Transform';
import { Vec2Value } from './Vec2';
import { Vec3Value } from './Vec3';
export declare function vec2(x: number, y: number): Vec2Value;
export declare function vec3(x: number, y: number, z: number): Vec3Value;
export declare function rotation(angle: number): RotValue;
export declare function setVec2(out: Vec2Value, x: number, y: number): Vec2Value;
export declare function copyVec2(out: Vec2Value, w: Vec2Value): Vec2Value;
export declare function zeroVec2(out: Vec2Value): Vec2Value;
export declare function negVec2(out: Vec2Value): Vec2Value;
export declare function plusVec2(out: Vec2Value, w: Vec2Value): Vec2Value;
export declare function addVec2(out: Vec2Value, v: Vec2Value, w: Vec2Value): Vec2Value;
export declare function minusVec2(out: Vec2Value, w: Vec2Value): Vec2Value;
export declare function subVec2(out: Vec2Value, v: Vec2Value, w: Vec2Value): Vec2Value;
export declare function mulVec2(out: Vec2Value, m: number): Vec2Value;
export declare function scaleVec2(out: Vec2Value, m: number, w: Vec2Value): Vec2Value;
export declare function plusScaleVec2(out: Vec2Value, m: number, w: Vec2Value): Vec2Value;
export declare function minusScaleVec2(out: Vec2Value, m: number, w: Vec2Value): Vec2Value;
export declare function combine2Vec2(out: Vec2Value, am: number, a: Vec2Value, bm: number, b: Vec2Value): Vec2Value;
export declare function combine3Vec2(out: Vec2Value, am: number, a: Vec2Value, bm: number, b: Vec2Value, cm: number, c: Vec2Value): Vec2Value;
export declare function normalizeVec2Length(out: Vec2Value): number;
export declare function normalizeVec2(out: Vec2Value): Vec2Value;
export declare function crossVec2Num(out: Vec2Value, v: Vec2Value, w: number): Vec2Value;
export declare function crossNumVec2(out: Vec2Value, w: number, v: Vec2Value): Vec2Value;
export declare function crossVec2Vec2(a: Vec2Value, b: Vec2Value): number;
export declare function dotVec2(a: Vec2Value, b: Vec2Value): number;
export declare function lengthVec2(a: Vec2Value): number;
export declare function lengthSqrVec2(a: Vec2Value): number;
export declare function distVec2(a: Vec2Value, b: Vec2Value): number;
export declare function distSqrVec2(a: Vec2Value, b: Vec2Value): number;
export declare function dotVec3(v: Vec3Value, w: Vec3Value): number;
export declare function setRotAngle(out: RotValue, a: number): RotValue;
export declare function rotVec2(out: Vec2Value, q: RotValue, v: Vec2Value): Vec2Value;
export declare function derotVec2(out: Vec2Value, q: RotValue, v: Vec2Value): Vec2Value;
export declare function rerotVec2(out: Vec2Value, before: RotValue, after: RotValue, v: Vec2Value): Vec2Value;
export declare function transform(x: number, y: number, a: number): TransformValue;
export declare function copyTransform(out: TransformValue, transform: TransformValue): TransformValue;
export declare function transformVec2(out: Vec2Value, xf: TransformValue, v: Vec2Value): Vec2Value;
export declare function detransformVec2(out: Vec2Value, xf: TransformValue, v: Vec2Value): Vec2Value;
export declare function retransformVec2(out: Vec2Value, from: TransformValue, to: TransformValue, v: Vec2Value): Vec2Value;
export declare function detransformTransform(out: TransformValue, a: TransformValue, b: TransformValue): TransformValue;
