import { glMatrix } from 'gl-matrix';
import { Matrix2D } from './Matrix2D';
export type Vector2Like = Float32Array | number[];
export interface Vector2 {
}
export declare class Vector2 extends Float32Array {
    static toRadian: typeof glMatrix.toRadian;
    static toDegree: typeof glMatrix.toDegree;
    static default(): Vector2;
    static create(x?: number, y?: number): Vector2;
    static fromRadian(rad: number): Vector2;
    static fromDegree(deg: number): Vector2;
    static fromVectorLike(vec: Vector2Like): Vector2;
    _onChange?: (v: Vector2) => void;
    constructor(x?: number, y?: number);
    set x(v: number);
    get x(): number;
    set y(v: number);
    get y(): number;
    onChange(callback: (v: Vector2) => void | null): this;
    private change;
    copy(v: Vector2Like): this;
    clone(): Vector2;
    set(x: any, y: any): this;
    add(v: Vector2Like): this;
    addVectors(a: Vector2Like, b: Vector2Like): this;
    subtract(v: Vector2Like): this;
    subtractVectors(a: Vector2Like, b: Vector2Like): this;
    multiplyScalar(s: number): this;
    divideScalar(s: number): this;
    multiply(v: Vector2Like): this;
    multiplyVectors(a: Vector2Like, b: Vector2Like): this;
    divide(v: Vector2Like): this;
    divideVectors(a: Vector2Like, b: Vector2Like): this;
    dot(v: Vector2Like): number;
    cross(v: Vector2Like): number;
    squareMagnitude(): number;
    magnitude(): number;
    normalize(): this;
    angle(): number;
    angleDegree(): number;
    distance(other: Vector2Like): number;
    squareDistance(other: Vector2Like): number;
    manhattanDistance(other: Vector2Like): number;
    chebyshevDistance(other: Vector2Like): number;
    lerp(v: Vector2Like, alpha: number): this;
    translate(x: number, y: number): this;
    perpendicular(): this;
    ccw(): this;
    cw(): this;
    negate(): this;
    floor(): this;
    ceil(): this;
    round(): this;
    min(v: Vector2Like): this;
    max(v: Vector2Like): this;
    projectOnVector(vector: Vector2Like): this;
    projectOnDirection(direction: Vector2Like): this;
    reflect(normal: Vector2Like): this;
    applyMatrix(m: Matrix2D): this;
    equals(v: Vector2Like): boolean;
    equalsWithEpsilon(v: Vector2Like, epsilon?: number): boolean;
    toString(): string;
}
