export declare class Int64 {
    private high_;
    private low_;
    constructor(low: number, high: number);
    get high(): number;
    get low(): number;
    clone(): Int64;
    isZero(): boolean;
    isNegative(): boolean;
    isPositive(): boolean;
    isOdd(): boolean;
    equals(other: Int64): boolean;
    notEquals(other: Int64): boolean;
    not(): Int64;
    neg(): Int64;
    negate(): Int64;
    and(other: Int64): Int64;
    or(other: Int64): Int64;
    xor(other: Int64): Int64;
    add(b: Int64 | number): Int64;
    sub(b: Int64 | number): Int64;
    subtract(b: Int64): Int64;
    mul(b: Int64 | number): Int64;
    multiply(b: Int64): Int64;
    div(b: Int64 | number): Int64;
    divide(b: Int64): Int64;
    mod(b: Int64): Int64;
    modulo(b: Int64): Int64;
    shr(b: number): Int64;
    shrUnsigned(b: number): Int64;
    shl(b: number): Int64;
    rotr(b: number): Int64;
    rotl(b: number): Int64;
    clz(): Int64;
    ctz(): Int64;
    compare(other: Int64): number;
    lessThan(other: Int64): boolean;
    lessThanOrEqual(other: Int64): boolean;
    greaterThan(other: Int64): boolean;
    greaterThanOrEqual(other: Int64): boolean;
    abs(): Int64;
    static fromNumber(value: number): Int64;
    static fromRoundNumber(value: number): Int64;
    static fromInt(value: number): Int64;
    private static fromString;
    toNumber(): number;
    toInt(): number;
    toString(radix?: number): string;
    static Swap(one: Int64, other: Int64): void;
    static max(a: Int64, b: Int64): Int64;
    static min(a: Int64, b: Int64): Int64;
    static init(): Promise<void>;
}
export declare class Int128 {
    private d0_;
    private d1_;
    private d2_;
    private d3_;
    constructor(d0: number, d1: number, d2: number, d3: number);
    get d0(): number;
    get d1(): number;
    get d2(): number;
    get d3(): number;
    clone(): Int128;
    isZero(): boolean;
    isNegative(): boolean;
    isPositive(): boolean;
    isOdd(): boolean;
    equals(other: Int128): boolean;
    notEquals(other: Int128): boolean;
    not(): Int128;
    neg(): Int128;
    negate(): Int128;
    and(b: Int128): Int128;
    or(b: Int128): Int128;
    xor(b: Int128): Int128;
    add(b: Int128): Int128;
    sub(b: Int128): Int128;
    subtract(b: Int128): Int128;
    compare(other: Int128): number;
    lessThan(b: Int128): boolean;
    lessThanOrEqual(b: Int128): boolean;
    greaterThan(b: Int128): boolean;
    greaterThanOrEqual(b: Int128): boolean;
    mul(b: Int128): Int128;
    multiply(b: Int128): Int128;
    shiftLeft(numBits: number): Int128;
    shiftRight(numBits: number): Int128;
    shiftRightUnsigned(numBits: number): Int128;
    toNumber(): number;
    abs(): Int128;
    static fromInt64(v: Int64): Int128;
    static fromNumber(value: number): Int128;
    static fromRoundNumber(value: number): Int128;
    static fromInt(value: number): Int128;
    static mul64(a: Int64, b: Int64): Int128;
    static Swap(one: Int128, other: Int128): void;
    static max(a: Int128, b: Int128): Int128;
    static min(a: Int128, b: Int128): Int128;
}
