import { BaseRenderer } from '../../../../../../../src/base/BaseRenderer';
import { CanvasKit } from '../../../../../../../src/canvaskit';
import { CanvaskitRendererOptions, CanvaskitRendererEvents, FillStrokeValue, CanvasDrawStyle } from '../../../../../../../src/types/Renderer';
import { DisplayObject } from '../../../../../../../src/scene/DisplayObject';
import { ConicGradient, LinearGradient, RadialGradient } from '../../../../../../../src/core/Gradient';
import { Color } from '../../../../../../../src/math/Color';
import { Pattern, PatternRepeat } from '../../../../../../../src/core/Pattern';
import { LineJoin, LineCap, FillRule, GlobalCompositeOperation } from '../../../../../../../src/enum';
import { Path2D } from '../../../../../../../src/canvaskit/htmlcanvas/path2d';
import { default as FontManager } from '../../../../../../../src/core/FontManager';
import { Image } from '../../../../../../../src/core/Image';
export declare class CanvaskitRenderer extends BaseRenderer<CanvaskitRendererOptions, CanvaskitRendererEvents> {
    static CK: CanvasKit.CanvasKit;
    surface: CanvasKit.Surface;
    canvas: CanvasKit.Canvas;
    ck: CanvasKit.CanvasKit;
    private disposableManager;
    _currentPath: CanvasKit.Path;
    _paint: CanvasKit.Paint;
    private _currentTransform;
    private _stateStack;
    globalAlpha: number;
    private _globalCompositeOperation;
    private _strokeWidth;
    private _miterLimit;
    private _lineDash;
    private _lineDashOffset;
    private _fillStyle;
    private _strokeStyle;
    _shadowColor: Color;
    shadowBlur: number;
    shadowOffsetX: number;
    shadowOffsetY: number;
    _fontMgr: FontManager;
    private _fontString;
    constructor(options: CanvaskitRendererOptions);
    initialize(): Promise<void>;
    loadFontFromUrl(fontUrl: string): Promise<CanvasKit.Typeface>;
    set globalCompositeOperation(value: GlobalCompositeOperation);
    get globalCompositeOperation(): GlobalCompositeOperation;
    set lineWidth(value: number);
    get lineWidth(): number;
    set miterLimit(value: number);
    get miterLimit(): number;
    set lineJoin(value: LineJoin);
    get lineJoin(): LineJoin;
    set lineCap(value: LineCap);
    get lineCap(): LineCap;
    setLineDash(segments: number[]): void;
    set LineDash(value: number[]);
    get LineDash(): number[];
    set lineDashOffset(value: number);
    get lineDashOffset(): number;
    set fillStyle(value: FillStrokeValue);
    get fillStyle(): FillStrokeValue;
    set strokeStyle(value: FillStrokeValue);
    get strokeStyle(): FillStrokeValue;
    get _font(): CanvasKit.Font;
    get font(): string;
    set font(newFont: string);
    get shadowColor(): Color;
    set shadowColor(value: string | null | 'none');
    createCanvaskitPath(): CanvasKit.Path;
    createCanvaskitPaint(): CanvasKit.Paint;
    clearRect(x: number, y: number, width: number, height: number): void;
    drawRect(x: number, y: number, width: number, height: number): void;
    createLinearGradient(x0: number, y0: number, x1: number, y1: number): LinearGradient;
    createRadialGradient(x0: number, y0: number, r0: number, x1: number, y1: number, r1: number): RadialGradient;
    createConicGradient(startAngle: number, x: number, y: number): ConicGradient;
    createPattern(image: CanvasImageSource, repetition: PatternRepeat): Pattern;
    translate(dx: number, dy: number): void;
    scale(sx: number, sy: number): void;
    rotate(angle: number): void;
    getCurrentTransform(): number[];
    setTransform(a: number, b: number, c: number, d: number, e: number, f: number): void;
    transform(a: number, b: number, c: number, d: number, e: number, f: number): void;
    resetTransform(): void;
    beginPath(): void;
    moveTo(x: number, y: number): void;
    lineTo(x: number, y: number): void;
    quadraticCurveTo(cp1x: number, cp1y: number, x: number, y: number): void;
    bezierCurveTo(cp1x: number, cp1y: number, cp2x: number, cp2y: number, x: number, y: number): void;
    rect(x: number, y: number, width: number, height: number): void;
    roundRect(x: number, y: number, width: number, height: number, radius: number | number[]): void;
    arc(x: number, y: number, radius: number, startAngle: number, endAngle: number, clockwise: boolean): void;
    arcTo(x1: number, y1: number, x2: number, y2: number, radius: number): void;
    ellipse(x: number, y: number, rx: number, ry: number, rotation: number, startAngle: number, endAngle: number, clockwise: boolean): void;
    closePath(): void;
    clip(_path?: CanvasKit.Path | Path2D | FillRule, fillRule?: FillRule): void;
    applyPathBorderSide(path: CanvasKit.Path, style: CanvasDrawStyle): void;
    applyMask(obj: DisplayObject): void;
    applyClipPath(obj: DisplayObject): void;
    applyFontStyle(style: CanvasDrawStyle): void;
    applyCanvasStyle(style: CanvasDrawStyle): void;
    private drawOrder;
    drawTextPaint(text: string, x: number, y: number, style: CanvasDrawStyle): void;
    drawPathPaint(path: CanvasKit.Path, style: CanvasDrawStyle): void;
    _fillPaint(): CanvasKit.Paint;
    _strokePaint(): CanvasKit.Paint;
    _shadowPaint(basePaint: CanvasKit.Paint): CanvasKit.Paint;
    _applyShadowOffsetMatrix(): void;
    fill(_path?: CanvasKit.Path | Path2D | FillRule, fillRule?: FillRule): void;
    stroke(_path?: CanvasKit.Path | Path2D): void;
    strokeRect(x: number, y: number, width: number, height: number): void;
    fillRect(x: number, y: number, width: number, height: number): void;
    fillText(text: string, x: number, y: number, maxWidth?: number): void;
    strokeText(text: string, x: number, y: number, maxWidth?: number): void;
    drawParagraph(paragraph: CanvasKit.Paragraph, x: number, y: number): void;
    measureText(text: string): {
        width: number;
    };
    drawImage(canvasImageSource: CanvasImageSource | Image, dx: number, dy: number): void;
    drawImage(canvasImageSource: CanvasImageSource | Image, dx: number, dy: number, dw: number, dh: number): void;
    drawImage(canvasImageSource: CanvasImageSource | Image, sx: number, sy: number, sw: number, sh: number, dx: number, dy: number, dw: number, dh: number): void;
    putImageData(imageData: ImageData, x: number, y: number, dirtyX: number, dirtyY: number, dirtyWidth: number, dirtyHeight: number): void;
    getImageData(x: number, y: number, w: number, h: number): ImageData;
    _mapToLocalCoordinates(pts: number[]): number[];
    isPointInPath(x: number, y: number, fillmode: string): boolean;
    save(): void;
    restore(): void;
    transformObject(object: DisplayObject): void;
    renderObject(object: DisplayObject): void;
    render({ renderObjects, delta }: {
        renderObjects: DisplayObject[];
        delta: number;
    }): void;
    dispose(): void;
}
