import { CanvasKit } from '../index';
import { HTMLImage } from './htmlimage';
import { Path2D } from './path2d';
import { RadialCanvasGradient } from './radialgradient';
import { CanvasPattern } from './pattern';
import { LinearCanvasGradient } from './lineargradient';
import { ImageData } from './imagedata';
declare module 'canvaskit-wasm' {
    interface Paint {
        dispose(): void;
    }
}
export declare class CanvasRenderingContext2D {
    _canvas: CanvasKit.Canvas;
    _paint: CanvasKit.Paint;
    _fontString: string;
    _font: CanvasKit.Font;
    _strokeStyle: any;
    _fillStyle: any;
    _shadowBlur: number;
    _shadowColor: CanvasKit.Color;
    _shadowOffsetX: number;
    _shadowOffsetY: number;
    _globalAlpha: number;
    _strokeWidth: number;
    _lineDashOffset: number;
    _lineDashList: number[];
    _globalCompositeOperation: CanvasKit.BlendMode;
    _currentPath: CanvasKit.Path;
    _currentTransform: number[];
    _canvasStateStack: any[];
    _toCleanUp: any[];
    constructor(skcanvas: CanvasKit.Canvas);
    _dispose(): void;
    get currentTransform(): {
        a: number;
        c: number;
        e: number;
        b: number;
        d: number;
        f: number;
    };
    set currentTransform(matrix: {
        a: number;
        c: number;
        e: number;
        b: number;
        d: number;
        f: number;
    });
    get fillStyle(): any;
    set fillStyle(newStyle: any);
    get font(): string;
    set font(newFont: string);
    get globalAlpha(): number;
    set globalAlpha(newAlpha: number);
    get globalCompositeOperation(): string;
    set globalCompositeOperation(newMode: string);
    get imageSmoothingEnabled(): boolean;
    get imageSmoothingQuality(): string;
    get lineCap(): string;
    set lineCap(newCap: string);
    get lineDashOffset(): number;
    set lineDashOffset(newOffset: number);
    get lineJoin(): CanvasLineJoin;
    set lineJoin(newJoin: CanvasLineJoin);
    get lineWidth(): number;
    set lineWidth(newWidth: number);
    get miterLimit(): number;
    set miterLimit(newLimit: number);
    get shadowBlur(): number;
    set shadowBlur(newBlur: number);
    get shadowColor(): string;
    set shadowColor(newColor: string);
    get shadowOffsetX(): number;
    set shadowOffsetX(newOffset: number);
    get shadowOffsetY(): number;
    set shadowOffsetY(newOffset: number);
    get strokeStyle(): any;
    set strokeStyle(newStyle: any);
    arc(x: number, y: number, radius: number, startAngle: number, endAngle: number, ccw: boolean): void;
    arcTo(x1: number, y1: number, x2: number, y2: number, radius: number): void;
    beginPath(): void;
    bezierCurveTo(cp1x: number, cp1y: number, cp2x: number, cp2y: number, x: number, y: number): void;
    clearRect(x: number, y: number, width: number, height: number): void;
    clip(path: any, fillRule: string): void;
    closePath(): void;
    createImageData(): ImageData;
    createLinearGradient(x1: number, y1: number, x2: number, y2: number): LinearCanvasGradient;
    createPattern(image: HTMLImage, repetition: any): CanvasPattern;
    createRadialGradient(x1: number, y1: number, r1: number, x2: number, y2: number, r2: number): RadialCanvasGradient;
    drawImage(img: CanvasKit.Image | HTMLImage): void;
    ellipse(x: number, y: number, radiusX: number, radiusY: number, rotation: number, startAngle: number, endAngle: number, ccw: boolean): void;
    _fillPaint(): CanvasKit.Paint;
    fill(path?: CanvasKit.Path | Path2D, fillRule?: string): void;
    fillRect(x: number, y: number, width: number, height: number): void;
    fillText(text: string, x: number, y: number, maxWidth: number): void;
    getImageData(x: number, y: number, w: number, h: number): ImageData;
    getLineDash(): number[];
    _mapToLocalCoordinates(pts: number[]): number[];
    isPointInPath(x: number, y: number, fillmode: string): boolean;
    isPointInStroke(x: number, y: number): boolean;
    lineTo(x: number, y: number): void;
    measureText(text: string): {
        width: number;
    };
    moveTo(x: number, y: number): void;
    putImageData(imageData: ImageData, x: number, y: number, dirtyX: number, dirtyY: number, dirtyWidth: number, dirtyHeight: number): void;
    quadraticCurveTo(cpx: number, cpy: number, x: number, y: number): void;
    rect(x: number, y: number, width: number, height: number): void;
    resetTransform(): void;
    restore(): void;
    rotate(radians: number): void;
    save(): void;
    scale(sx: number, sy: number): void;
    setLineDash(dashes: number[]): void;
    setTransform(a: number, b: number, c: number, d: number, e: number, f: number): void;
    _applyShadowOffsetMatrix(): void;
    _shadowPaint(basePaint: CanvasKit.Paint): CanvasKit.Paint;
    _strokePaint(): CanvasKit.Paint;
    stroke(newpath?: Path2D): void;
    strokeRect(x: number, y: number, width: number, height: number): void;
    strokeText(text: string, x: number, y: number, maxWidth: number): void;
    translate(dx: number, dy: number): void;
    transform(a: number, b: number, c: number, d: number, e: number, f: number): void;
    addHitRegion(): void;
    clearHitRegions(): void;
    drawFocusIfNeeded(): void;
    removeHitRegion(): void;
    scrollPathIntoView(): void;
}
